pip install lxml

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os; os.chdir('/home/jovyan/work/ufc')
# os.chdir('C:\\Users\\admin\\Documents\\work\\python\\progs\\scraper\\ufc\\')
# import os; os.chdir('C:\\work\\dev\\python\\progs\\scraper\\ufc')

In [3]:
from bs4 import BeautifulSoup
from datetime import datetime

import numpy as np
import pandas as pd
import re

In [4]:
import requests

In [5]:
from omegaconf import OmegaConf

conf = OmegaConf.load('params.yaml')

# fights coefs

In [8]:
url = 'https://leon.ru/api-2/betline/events/all?ctag=ru-RU&league_id=1970324837036957&hideClosed=true&flags=reg,urlv2,mm2,rrc,nodup'
# url = 'https://leon.ru/api-2/betline/events/all?ctag=ru-RU&region_id=1970324852975455&hideClosed=true&flags=reg,urlv2,mm2,rrc,nodup'
headers = {
    "accept": "*/*",
    "accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
    "priority": "u=1, i",
    "referer": "https://leon.ru/bets/mma/1970324836974960-ufc",
    "sec-ch-ua": '"Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"',
    "sec-ch-ua-mobile": "?1",
    "sec-ch-ua-platform": '"Android"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Mobile Safari/537.36",
    "x-app-browser": "chrome",
    "x-app-env": "prod",
    "x-app-language": "ru_RU",
    "x-app-layout": "phone",
    "x-app-modernity": "legacy",
    "x-app-os": "android",
    "x-app-platform": "web",
    "x-app-rendering": "csr",
    "x-app-skin": "default",
    "x-app-theme": "LIGHT",
    "x-app-version": "6.113.2",
    "x-requested-uri": "/bets/mma/1970324836974960-ufc"
}

cookies = {
    "__ddg1_": "aKv0JIzXhx2QEKciyhtm",
    "ABTestSeed": "37",
    "wm": "62398954",
    "click_id": "d75043555d8b576b57d00d5b",
    "ipfrom": "185.222.238.69",
    "referer": "https://bookmaker-ratings.ru/",
    "x-app-language": "ru_RU",
    "firstTheme": "LIGHT",
    "_ga": "GA1.1.803396759.1744464327",
    "_ym_uid": "1744464328338270285",
    "_ym_d": "1744464328",
    "qtag_rfrr": "null-null",
    "__ddg9_": "109.252.121.163",
    "_ym_isad": "2",
    "_ga_THNYNGV4VN": "GS2.1.s1748668513$o9$g1$t1748668821$j43$l0$h0",
    "__ddg10_": "1748668887",
    "__ddg8_": "dIW8Z0YF7bfSeQGV"
}

response = requests.get(url, headers=headers, cookies=cookies)

if response.status_code == 200:
    print("Request successful!")
    res_js = response.json()

Request successful!

In [9]:
event_date = datetime.fromtimestamp(res_js['events'][0]['kickoff']/1000)
event_date = event_date.strftime('%d.%m.%Y')
event_name = res_js['events'][0]['league']['name']
load_date = datetime.now().strftime('%Y-%m-%d')

In [10]:
res_l = []
for i in range(len(res_js['events'])):
    s = []
    fight = res_js['events'][i]
    # fighters = [it['name'] for it in res_js['events'][i]['competitors']]
    fighters = [it['name'] for it in fight['competitors'] if it['homeAway']=='HOME'] + [it['name'] for it in fight['competitors'] if it['homeAway']=='AWAY']
    # coefs = [it['price'] for it in res_js['events'][i]['markets'][0]['runners']]
    coefs = [it['price'] for it in fight['markets'][0]['runners'] if 'HOME' in it['tags']] + [it['price'] for it in fight['markets'][0]['runners'] if 'AWAY' in it['tags']]

    s.extend(fighters)
    s.extend(coefs)
    s.extend([event_date])
    s.extend([load_date])
    s.extend([event_name])
    s.extend(['leon.ru'])
    
    
    res_l.append(s)



fighter_coef_df = pd.DataFrame(res_l, columns=['fighter1', 'fighter2', 'coef1', 'coef2', 'date', 'load_date', 'name', 'source'])
fighter_coef_df

,fighter1,fighter2,coef1,coef2,date,load_date,name,source
0,Дельфин Бенуайш,София Монтенегро,1.66,2.19,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
1,Матье Лето Дюкло,Диас Л Ф,1.87,1.91,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
2,Нора Корноль,"Сигула, Клаудия",1.79,1.99,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
3,Майкл Альжаруж,Фабия Синтес,1.74,2.06,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
4,Натаниэль Вуд,Павел Андруска,1.28,3.60,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
5,Омар Си,Модестас Букаускас,1.45,2.70,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
6,Мариу Пинту,Райан Спэнн,1.32,3.30,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
7,Морган Шарьер,Фелипе Лима,2.46,1.53,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
8,Лосене Кейта,Мухаммад Наимов,1.27,3.65,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
9,Кертис Кэмпбелл,Тревор Пик,1.24,3.90,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
10,Даниил Донченко,Пунахили Сориано,1.38,2.95,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
11,Майкл Пэйдж,Нурсултон Рузибоев,1.60,2.30,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
12,Фарес Зиам,Аксель Сола,1.64,2.22,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru
13,Дэн Хукер,Саладин Парнасс,5.20,1.15,05.09.2026,2026-09-03,UFC Fight Night: Хукер - Парнасс,leon.ru

In [21]:
df_prev = pd.read_excel(conf['inference']['coef_fn'])

In [22]:
df_all = pd.concat([df_prev, fighter_coef_df], ignore_index=True)
df_all['coef1'] = df_all['coef1'].astype(float)

df_all['coef2'] = df_all['coef2'].astype(float)
# нули и пустоты удалить потом

df_all.tail()

,fighter1,fighter2,coef1,coef2,date,name,load_date,source
2042,Морган Шарьер,Фелипе Лима,2.60,1.48,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru
2043,Даниил Донченко,Пунахили Сориано,1.37,3.05,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru
2044,Майкл Пэйдж,Нурсултон Рузибоев,1.53,2.46,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru
2045,Фарес Зиам,Аксель Сола,1.63,2.24,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru
2046,Дэн Хукер,Саладин Парнасс,5.00,1.16,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru

In [23]:
df_all.to_excel(conf['inference']['coef_fn'], index=False)

# UFC rankings

from selenium import webdriver
# тут драйвера - c:\work\dev\python\progs\utils\
# browser = webdriver.Firefox()
browser = webdriver.Chrome()

from selenium import webdriver
from selenium.webdriver.chrome.service import Service

PROXY = "5.129.232.80:4080"          # <host>:<port>

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument(f'--proxy-server=http://{PROXY}')   # http

service = Service(r'c:\work\dev\python\progs\utils\chromedriver.exe')
browser = webdriver.Chrome(service=service, options=chrome_options)

import shutil
from pathlib import Path

cache = Path.home() / ".cache" / "selenium" / "firefox" / "win64"
if cache.exists():
    versions = sorted((p for p in cache.iterdir() if p.is_dir()))
    for old in versions[:-1]:  # оставляем самую свежую
        shutil.rmtree(old, ignore_errors=True)

In [6]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.proxy import Proxy, ProxyType

# driver = webdriver.Firefox()

# Настройки прокси
# proxy_ip = "5.129.232.80"
proxy_ip = "217.177.72.248"
proxy_port = "4080"

proxy = Proxy()
proxy.proxy_type = ProxyType.MANUAL
proxy.http_proxy = f"{proxy_ip}:{proxy_port}"
proxy.ssl_proxy = f"{proxy_ip}:{proxy_port}"  # Для HTTPS сайтов
proxy.ftp_proxy = f"{proxy_ip}:{proxy_port}"  # Опционально

# Применяем прокси к опциям
firefox_options = Options()
firefox_options.add_argument("--headless")
# firefox_options.proxy = proxy

# Запускаем драйвер
browser = webdriver.Firefox(options=firefox_options)

In [7]:
browser.get('https://ufc.ru/rankings')
# browser.implicitly_wait(2)
html = browser.page_source

In [8]:
bsObj = BeautifulSoup(html, 'lxml')

weights = bsObj.findAll('tbody')
info_headers = bsObj.findAll('div', {'class':'info'})

In [27]:
fin_l = []
for i in range(len(info_headers)):
    division_name = info_headers[i].h4.get_text()
    slice_date = datetime.now().strftime('%Y-%m-%d')

    pattern1 = r'\n(\d+)\s+\n([^\n]+)\s+\nRank (increased|decreased) by (\d+)\s+'
    pattern2 = r'\n(\d+)\s+\n([^\n]+)\s+\n[^R]+\n'
    
    
    weight_strs = [it.get_text() for it in weights[i].findAll('tr')]
    
    main_name = info_headers[i].h5.get_text()

    if not 'вне' in division_name.lower():
        fin_l.append((main_name, 0, None, np.nan, division_name, slice_date))
    
    for text in weight_strs:
        match1 = re.search(pattern1, text)
        match2 = re.search(pattern2, text)
        if match1:
            rank = match1.group(1)
            name = match1.group(2)      # 'Илия Топурия'
            direction = match1.group(3)    # 'increased'
            amount = match1.group(4)    # '2'
            fin_l.append((name, rank, direction, amount, division_name, slice_date))
        elif match2:
            rank = match2.group(1)
            name = match2.group(2)
            fin_l.append((name, rank, None, np.nan, division_name, slice_date))
        else:
            fin_l.append((None, np.nan, None, np.nan, division_name, slice_date))

rank_df = pd.DataFrame(fin_l, columns=['name', 'rank', 'direction', 'val', 'division_name', 'date'])

C:\Users\admin\AppData\Local\Temp\ipykernel_19212\1696872215.py:10: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  weight_strs = [it.get_text() for it in weights[i].findAll('tr')]

## проверки

In [28]:
assert rank_df.isna().mean().loc[lambda x: x>0].index.tolist()==['direction', 'val'], 'Состав null полей поменялся'

In [29]:
assert ((rank_df==0).mean().loc[lambda x: x>0]).between(0.05, 0.07).iloc[0]==True, 'Пропорция нулевых рангов изменилась'

In [30]:
assert (rank_df=='').mean().loc[lambda x: x>0].shape[0]==0, 'Появились пустые строки'

In [31]:
rank_df.head(5)

                name rank direction  val     division_name        date
0         Джошуа Ван    0      None  NaN  Наилегчайший вес  2026-08-31
1  Александр Пантожа    1      None  NaN  Наилегчайший вес  2026-08-31
2       Манель Кейпе    2      None  NaN  Наилегчайший вес  2026-08-31
3     Брэндон Ройвал    3      None  NaN  Наилегчайший вес  2026-08-31
4      Татсуро Таира    4      None  NaN  Наилегчайший вес  2026-08-31

## сохранение

In [32]:
rank_old_df = pd.read_csv(conf['inference']['rankings_fn'])
rank_df = pd.concat([rank_old_df, rank_df], ignore_index=True, axis=0)

In [33]:
rank_old_df.shape, rank_df.shape

((11446, 6), (11828, 6))

In [34]:
import shutil

shutil.move(conf['inference']['rankings_fn'], f'data/arch/rank_df_{slice_date}.csv')
rank_df.to_csv(conf['inference']['rankings_fn'], index=False)

In [35]:
rank_df[(rank_df.division_name=='Вне зависимости от категорий Top Rank')&(rank_df['date']==rank_df['date'].max())].head(10)

,name,rank,direction,val,division_name,date
11622,Ислам Махачев,1,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11623,Александр Волкановски,2,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11624,Пётр Ян,3,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11625,Джастин Гейджи,4,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11626,Илия Топурия,5,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11627,Том Аспинэлл,6,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11628,Шон Стрикланд,7,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11629,Мераб Двалишвили,8,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11630,Алекс Перейра,9,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31
11631,Сирил Ган,10,None,NaN,Вне зависимости от категорий Top Rank,2026-08-31

# Topology rankings

In [36]:
from datetime import datetime

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.proxy import Proxy, ProxyType

# driver = webdriver.Firefox()

# Настройки прокси
# proxy_ip = "5.129.232.80"
proxy_ip = "217.177.72.248"
proxy_port = "4080"

proxy = Proxy()
proxy.proxy_type = ProxyType.MANUAL
proxy.http_proxy = f"{proxy_ip}:{proxy_port}"
proxy.ssl_proxy = f"{proxy_ip}:{proxy_port}"  # Для HTTPS сайтов
proxy.ftp_proxy = f"{proxy_ip}:{proxy_port}"  # Опционально

# Применяем прокси к опциям
firefox_options = Options()
firefox_options.add_argument("--headless")
# firefox_options.proxy = proxy

# Запускаем драйвер
browser = webdriver.Firefox(options=firefox_options)

In [37]:
weights = {'heavyweight': 'https://www.tapology.com/rankings/current-top-ten-heavyweight-mma-fighters-265-pounds',
           'light-heavyweight':'https://www.tapology.com/rankings/current-top-ten-light-heavyweight-mma-fighters-205-pounds',
            'middleweight':'https://www.tapology.com/rankings/current-top-ten-middleweight-mma-fighters-185-pounds',
            'welterweight':'https://www.tapology.com/rankings/current-top-ten-welterweight-mma-fighters-170-pounds',
            'lightweight':'https://www.tapology.com/rankings/current-top-ten-lightweight-mma-fighters-155-pounds',
            'featherweight':'https://www.tapology.com/rankings/current-top-ten-featherweight-mma-fighters-145-pounds',
            'bantamweight':'https://www.tapology.com/rankings/current-top-ten-bantamweight-mma-fighters-135-pounds',
            'flyweight':'https://www.tapology.com/rankings/35-top-flyweight-mma-fighters',
            'women-bantamweight':'https://www.tapology.com/rankings/1261-top-women-bantamweight-fighters',
            'women-flyweight':'https://www.tapology.com/rankings/1262-top-women-flyweight-fighters',
            'women-strawweight':'https://www.tapology.com/rankings/1263-top-women-strawweight-fighters',
            'women-atomweight':'https://www.tapology.com/rankings/1264-top-women-atomweight-fighters',
            'women-featherweight':'https://www.tapology.com/rankings/1265-top-women-featherweight-fighters'
          }

In [38]:
%%time
N = 2
fighters = []

slice_date = datetime.now().strftime('%Y-%m-%d')
for weight in weights.keys():
    fighters_page_d = {}
    fighters_page_d['division_name'] = weight
    fighters_page_d['date'] = slice_date
    
    for page in range(1, N+1):
        browser.get(f'{weights[weight]}?page={page}&ranking=10')
        # browser.implicitly_wait(0.1)
        html = browser.page_source

        bsObj = BeautifulSoup(html, 'lxml')
        
        lis = bsObj.findAll('li', {'class':'rankingItemsItem'})
        for i, info in enumerate(lis):
            
            fighters_page_d['rank'] = info.find('p').get_text().strip()
            fighters_page_d['name'] = info.find('h1').get_text().strip()
            
            fighters.append(fighters_page_d.copy())

<timed exec>:17: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.

CPU times: total: 3.19 s
Wall time: 38.8 s

In [39]:
rank_big_df = pd.DataFrame(fighters)

## проверки

In [40]:
assert rank_big_df.loc[lambda x: x[['name', 'division_name']].duplicated(keep=False)].sort_values(by='name').shape[0] == 0, 'В рамках одного веса несколько записей о бойце'

In [41]:
assert len(rank_big_df['division_name'].unique())==13, 'Количество категорий поменялось'

In [42]:
assert rank_big_df.isna().mean().loc[lambda x: x>0].index.tolist()==[], 'Состав null полей поменялся'

In [43]:
assert ((rank_big_df==0).mean().loc[lambda x: x>0]).shape[0]==0, 'Нулевые ранги появились откуда-то'

In [44]:
assert (rank_big_df=='').mean().loc[lambda x: x>0].shape[0]==0, 'Появились пустые строки'

## сохранение

In [45]:
rank_big_old_df = pd.read_csv('data/inference/rank_big_df.csv', dtype='str')

In [46]:
rank_big_df = pd.concat([rank_big_old_df, rank_big_df], ignore_index=True, axis=0)

In [47]:
import shutil

shutil.move('data/inference/rank_big_df.csv', f'data/arch/rank_df_{slice_date}.csv')
rank_big_df.to_csv('data/inference/rank_big_df.csv', index=False)

In [48]:
rank_big_df.shape, rank_big_old_df.shape

((51544, 4), (50244, 4))

# Статистика бойцов

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.proxy import Proxy, ProxyType

# driver = webdriver.Firefox()

# Настройки прокси
# proxy_ip = "5.129.232.80"
proxy_ip = "217.177.72.248"
proxy_port = "4080"

proxy = Proxy()
proxy.proxy_type = ProxyType.MANUAL
proxy.http_proxy = f"{proxy_ip}:{proxy_port}"
proxy.ssl_proxy = f"{proxy_ip}:{proxy_port}"  # Для HTTPS сайтов
proxy.ftp_proxy = f"{proxy_ip}:{proxy_port}"  # Опционально

# Применяем прокси к опциям
firefox_options = Options()
firefox_options.add_argument("--headless")
# firefox_options.proxy = proxy

# Запускаем драйвер
browser = webdriver.Firefox(options=firefox_options)

In [49]:
slice_date = datetime.now().strftime('%Y-%m-%d')

In [52]:
%%time
chars = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

res = []

for i in range(len(chars)):
    url = f'http://ufcstats.com/statistics/fighters?char={chars[i]}&page=all'

    browser.get(url)
    browser.implicitly_wait(1)
    html = browser.page_source
    bsObj = BeautifulSoup(html, 'lxml')
    fighter_rows = bsObj.findAll('tr', {'class':'b-statistics__table-row'})
    
    vals = []
    for j, row in enumerate(fighter_rows):
        if j==0 and i==0:
            colnms = [it.get_text().strip() for it in row.findAll('th', {'class':'b-statistics__table-col'})][:-4]
        # j==1 empty
        elif j>1:
            link = [it.get('href') for it in row.findAll('a') if 'fighter-details' in it.get('href')][0]
            vals.append([it.get_text().strip() for it in row.findAll('td', {'class':'b-statistics__table-col'})][:-4] +[link])
            
        
    res.extend(vals)

<timed exec>:12: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
<timed exec>:17: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
<timed exec>:20: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
<timed exec>:21: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.

CPU times: total: 3.17 s
Wall time: 27.7 s

In [53]:
# fighters_stat_df = pd.DataFrame(res, columns=colnms+['link']).assign(slice_date=slice_date, dob=None)
fighters_stat_df = pd.DataFrame(res, columns=colnms+['link']).assign(slice_date=slice_date)

## проверки

In [54]:
assert len(set(chars) - set([it.lower() for it in fighters_stat_df['Last'].str[0].unique()]) )==0, 'Будто не все скачалось'

In [55]:
assert [it for it in fighters_stat_df['Last'].str[0].unique() if it.islower()] == ['d', 'v'], 'Есть маленькие буквы не только d, v'

In [56]:
assert fighters_stat_df.isna().mean().loc[lambda x: x>0].shape[0]==0, 'Нет nan-ов'

In [57]:
assert fighters_stat_df[~((fighters_stat_df.First=='Tony') & (fighters_stat_df.Last=='Johnson'))].duplicated(subset=['First', 'Last', 'Nickname']).sum() == 0 , 'Есть дубли по бойцам'

AssertionError: Есть дубли по бойцам

In [58]:
fighters_stat_df[~((fighters_stat_df.First=='Tony') & (fighters_stat_df.Last=='Johnson'))].loc[lambda x: x.duplicated(subset=['First', 'Last', 'Nickname'], keep=False)==True]

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,link,slice_date
1251,Anthony,Figueroa,,"5' 4""",135 lbs.,--,Orthodox,http://ufcstats.com/fighter-details/daff32bc96...,2026-08-31
1254,Anthony,Figueroa,,--,155 lbs.,--,,http://ufcstats.com/fighter-details/35e3a24591...,2026-08-31

In [59]:
assert (fighters_stat_df==0).sum().loc[lambda x: x>0].shape[0] == 0

In [60]:
(fighters_stat_df=='').mean().loc[lambda x: x>0]

First       0.003685
Nickname    0.441361
Stance      0.194234
dtype: float64

In [61]:
fighters_stat_df_s = fighters_stat_df.copy()

fighters_stat_df = fighters_stat_df_s.copy()

## добавление старого

In [62]:
fighters_stat_old_df = pd.read_csv('data/inference/fighters_stat_df.csv', keep_default_na=False)
fighters_stat_df = pd.concat([fighters_stat_old_df, fighters_stat_df], ignore_index=True, axis=0)

In [63]:
# удалили полные дубли
fighters_stat_df = fighters_stat_df[~fighters_stat_df.drop(columns=['slice_date', 'dob']).duplicated(keep='first')]

In [64]:
# Если True, тут интересно, так как дубли неполные, надо операции ниже тщательно посмотреть, как действуют на дублях
fighters_stat_df[(~((fighters_stat_df.First=='Tony') & (fighters_stat_df.Last=='Johnson')))&fighters_stat_df.duplicated(['First', 'Last', 'Nickname'], keep=False)].shape[0]==0

False

In [65]:
fighters_stat_df[(~((fighters_stat_df.First=='Tony') & (fighters_stat_df.Last=='Johnson')))
&fighters_stat_df.duplicated(['First', 'Last', 'Nickname'], keep=False)].sort_values(by=['First', 'Last', 'Nickname'])

,First,Last,Nickname,Ht.,Wt.,Reach,Stance,link,slice_date,dob
13,,Rongzhu,,"5' 9""",155 lbs.,"71.0""",Orthodox,http://ufcstats.com/fighter-details/a13d755965...,2025-07-12,"Mar 07, 2000"
8255,,Rongzhu,,"5' 9""",155 lbs.,"70.0""",Orthodox,http://ufcstats.com/fighter-details/a13d755965...,2026-08-31,NaN
140,Aleksandar,Rakic,Rocket,"6' 4""",205 lbs.,"78.0""",Orthodox,http://ufcstats.com/fighter-details/333b9e5c72...,2025-07-09,"Feb 06, 1992"
8073,Aleksandar,Rakic,Rocket,"6' 4""",238 lbs.,"78.0""",Orthodox,http://ufcstats.com/fighter-details/333b9e5c72...,2026-08-31,NaN
151,Alex,Apodaca,,--,135 lbs.,--,Switch,http://ufcstats.com/fighter-details/14a48a86b2...,2026-08-21,"Jun 30, 1994"
...,...,...,...,...,...,...,...,...,...,...
8650,YoungJae,Song,Super Rookie,"5' 8""",145 lbs.,"70.0""",Orthodox,http://ufcstats.com/fighter-details/0efb0d4ebb...,2026-08-31,NaN
4657,Yousri,Belgaroui,,"6' 5""",185 lbs.,"79.0""",Orthodox,http://ufcstats.com/fighter-details/7674b836ce...,2025-07-12,"Jun 02, 1992"
5063,Yousri,Belgaroui,,"6' 6""",185 lbs.,"79.0""",Orthodox,http://ufcstats.com/fighter-details/7674b836ce...,2026-08-31,NaN
4665,Yuji,Ephoevi-Ga,The Chef,"5' 9""",155 lbs.,"75.0""",Switch,http://ufcstats.com/fighter-details/919fc4bc3e...,2025-07-12,"Oct 19, 1999"
5886,Yuji,Ephoevi-Ga,The Chef,"6' 0""",155 lbs.,"75.0""",Switch,http://ufcstats.com/fighter-details/919fc4bc3e...,2026-08-31,NaN

In [66]:
# ищем короткие строки (пустые, nan) будем из дублей оставлять более заполненные
# dob не рассматриваем, просто потом скачаем снова, чтобы не париться
fighters_stat_df['short_ndob'] = fighters_stat_df.drop(columns='dob').astype(str).apply(lambda x: (x.str.len()<5).sum(), axis=1)
fighters_stat_df['short_dob'] = fighters_stat_df.astype(str).apply(lambda x: (x.str.len()<5).sum(), axis=1)
# fighters_stat_df.groupby(['First', 'Last', 'Nickname']).apply(lambda df: df[df.dob.notna()])

fighters_stat_df = fighters_stat_df.groupby(['First', 'Last', 'Nickname'], as_index=False).apply(lambda df: df.sort_values(by=['short_ndob', 'short_dob']).iloc[0])\
                                    .drop(columns=['short_ndob', 'short_dob'])

C:\Users\admin\AppData\Local\Temp\ipykernel_19212\2189846367.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fighters_stat_df = fighters_stat_df.groupby(['First', 'Last', 'Nickname'], as_index=False).apply(lambda df: df.sort_values(by=['short_ndob', 'short_dob']).iloc[0])\

### сравнение несовпадений с тем, что было

fighters_stat_df.sort_values(by=['First', 'Last', 'Nickname']).reset_index(drop=True).compare(fighters_stat_old_df.sort_values(by=['First', 'Last', 'Nickname']).reset_index(drop=True))

fighters_stat_df.merge(fighters_stat_old_df, on=fighters_stat_old_df.columns.tolist(), how='outer', indicator='ind').loc[lambda x: x['ind']!='both']

In [67]:
(fighters_stat_df['dob'].str.len()>10).sum()

np.int64(4199)

## сохранение

In [68]:
import shutil

shutil.move('data/inference/fighters_stat_df.csv', f'data/arch/fighters_stat_df_{slice_date}.csv')
fighters_stat_df.to_csv('data/inference/fighters_stat_df.csv', index=False)

## качаем dob

In [57]:
fighters_stat_df = pd.read_csv('data/inference/fighters_stat_df.csv', keep_default_na=False)

сконкатенируем со старым и для бойцов, у которых либо нет link-а в истории либо нет dob в истории делаем запрос

In [58]:
# fighters_dob = fighters_stat_df.groupby(['First', 'Last', 'Nickname']).apply(lambda x: (x['link']=='').mean()==1 or (x['dob']=='').mean()==1 or x['link'].isna().mean()==1 or x['dob'].isna().mean()==1).index
fighters_dob = fighters_stat_df[(fighters_stat_df.link.str.contains('http')) & ((fighters_stat_df.dob=='') | (fighters_stat_df.dob.isna()) )].set_index(['First', 'Last', 'Nickname']).index

fighters_dob_df = fighters_stat_df.set_index(['First', 'Last', 'Nickname']).loc[fighters_dob]
fighters_dob_df.shape

(652, 7)

In [59]:
%%time

res = []
for i in range(1, len(fighters_dob_df)):
    
    d = {}
    browser.get(fighters_dob_df['link'].iloc[i])
    browser.implicitly_wait(0.1)
    html = browser.page_source
    bsObj = BeautifulSoup(html, 'lxml')
    rows = bsObj.findAll('li', {'class':'b-list__box-list-item b-list__box-list-item_type_block'})
    dobel = [it for it in rows if 'DOB' in it.get_text()][0]
    try:
        dob = re.search(r'([A-Za-z]{3})\s+\d{1,2},\s+(\d{4})', dobel.get_text()).group(0)
    except: 
        dob = None
    s = fighters_dob_df.iloc[i].name
    d['First'] = s[0]
    d['Last'] = s[1]
    d['Nickname'] = s[2]
    d['dob'] = dob
    res.append(d)
    if i==1000:
        break

<timed exec>:9: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.

CPU times: total: 6.44 s
Wall time: 9min 7s

In [60]:
fighters_stat_df = fighters_stat_df.merge(pd.DataFrame(res), on=['First', 'Last', 'Nickname'], how='left')\
                .assign(dob=lambda x: np.where(x['dob_y'].notna(), x['dob_y'], x['dob_x']))\
                .drop(columns=['dob_y', 'dob_x'])

In [61]:
(fighters_stat_df['dob'].str.len()>10).sum()

np.int64(4219)

## сохранение

In [62]:
import shutil

shutil.move('data/inference/fighters_stat_df.csv', f'data/arch/fighters_stat_df_{slice_date}.csv')
fighters_stat_df.to_csv('data/inference/fighters_stat_df.csv', index=False)

1. Height: 5' 7"
Рост: 5 футов 7 дюймов ≈ 170 см

2. Weight: 135 lbs.
Вес: 135 фунтов ≈ 61,2 кг

3. Reach: 68"
Размах рук: 68 дюймов ≈ 173 см

4. Stance: Orthodox
Стойка: Обычная (правша)

5. DOB: Jan 28, 1996
Дата рождения: 28 января 1996 года

In [69]:
browser.quit()

# Агрегации коэффициентов

In [70]:
import pandas as pd
from io import StringIO

In [71]:
df= pd.read_excel(conf['inference']['coef_fn'])
df.tail(2)

,fighter1,fighter2,coef1,coef2,date,name,load_date,source
2045,Фарес Зиам,Аксель Сола,1.63,2.24,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru
2046,Дэн Хукер,Саладин Парнасс,5.00,1.16,05.09.2026,UFC Fight Night: Хукер - Парнасс,2026-08-31,leon.ru

In [72]:
print(df.loc[df.name=='UFC Fight Night: Хукер - Парнасс', ['fighter1', 'fighter2']].to_markdown(index=False))

| fighter1         | fighter2           |
|:-----------------|:-------------------|
| Майкл Альжаруж   | Фабия Синтес       |
| Дельфин Бенуайш  | София Монтенегро   |
| Матье Лето Дюкло | Диас Л Ф           |
| Нора Корноль     | Сигула, Клаудия    |
| Омар Си          | Модестас Букаускас |
| Кертис Кэмпбелл  | Тревор Пик         |
| Мариу Пинту      | Райан Спэнн        |
| Лосене Кейта     | Мухаммад Наимов    |
| Морган Шарьер    | Фелипе Лима        |
| Даниил Донченко  | Пунахили Сориано   |
| Майкл Пэйдж      | Нурсултон Рузибоев |
| Фарес Зиам       | Аксель Сола        |
| Дэн Хукер        | Саладин Парнасс    |

Найди в Интернете свежие коэффициенты букмекерских фирм России, Америки и Европы, Азии на поединки турнира "UFC Fight Night: Хукер - Парнасс", включающего бои из markdown таблицы ниже. 
Структурируй ответ по шагам: 
- Первый шаг составь список сайтов и ссылок на данные. Учитывай сайты из списка ниже, но не ограничивайся ими, обязательно ищи другие.
- Второй шаг проверь актуальность данных, перейдя по ссылкам, удостоверься в правильности коэффициентов и составь таблицу: ссылка, проверка пройдена (да/нет).
- Третий шаг составь таблицу из пар соперников для которых найдены коэффициенты и проверена валидность ссылок
- Четвертый шаг - для всех пары соперников из третьего шага, сформируй таблицу в формате csv с колонками имя первого бойца (название fighter1), имя второго бойца (fighter2), коэффициент на первого бойца (coef1), коэффициент на второго бойца (coef2), название источника (source) и ссылка их источника (link).
- Пятый, финальный шаг - сконкатенируй таблицы из четвертого шага и добавь текущую дату в формате %Y-%m-%d, как колонку load_date. хочу финал в отдельном csv поле для копирования

популярные сайты источники, коэффициенты нужно искать на их внутренних страницах:
https://www.forbes.com, https://mmajunkie.usatoday.com, https://pari.ru, https://www.mmaoddsbreaker.com, https://www.espn.com, https://fightodds.io, https://www.covers.com, https://sports.yahoo.com, https://www.bookmaker.eu, https://fon.bet, https://sportsbook.draftkings.com, https://www.bet365.com, https://www.oddsshark.com, https://www.tapology.com, https://verdictmma.com, https://winline.ru, https://www.betmgm.com, https://www.betonline.ag, https://www.bestfightodds.com, https://www.wagertalk.com', https://leon.ru/, https://winline.ru/, https://fon.bet/, https://www.ligastavok.ru/, https://pari.ru/, https://betboom.ru/

markdown таблица с боями:
| fighter1         | fighter2           |
|:-----------------|:-------------------|
| Майкл Альжаруж   | Фабия Синтес       |
| Дельфин Бенуайш  | София Монтенегро   |
| Матье Лето Дюкло | Диас Л Ф           |
| Нора Корноль     | Сигула, Клаудия    |
| Омар Си          | Модестас Букаускас |
| Кертис Кэмпбелл  | Тревор Пик         |
| Мариу Пинту      | Райан Спэнн        |
| Лосене Кейта     | Мухаммад Наимов    |
| Морган Шарьер    | Фелипе Лима        |
| Даниил Донченко  | Пунахили Сориано   |
| Майкл Пэйдж      | Нурсултон Рузибоев |
| Фарес Зиам       | Аксель Сола        |
| Дэн Хукер        | Саладин Парнасс    |

добавь все бои и прими во внимание перечисленные мной сайты там точно есть коэффициенты: https://www.forbes.com, https://mmajunkie.usatoday.com, https://pari.ru, https://www.mmaoddsbreaker.com, https://www.espn.com, https://fightodds.io, https://www.covers.com, https://sports.yahoo.com, https://www.bookmaker.eu, https://fon.bet, https://sportsbook.draftkings.com, https://www.bet365.com, https://www.oddsshark.com, https://www.tapology.com, https://verdictmma.com, https://winline.ru, https://www.betmgm.com, https://www.betonline.ag, https://www.bestfightodds.com, https://www.wagertalk.com', https://leon.ru/, https://winline.ru/, https://fon.bet/, https://www.ligastavok.ru/, https://pari.ru/, https://betboom.ru/

- load_date старая, ссылки не или туда старые даты входят
- коэффициенты сильно отличающиеся от других/
leon-а

## [ds](https://chat.deepseek.com/)

мало, но тщательнее

In [90]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Майкл Пэйдж,Нурсултон Рузибоев,1.64,2.44,Robinhood,https://robinhood.com/us/en/prediction-markets/mma/events/fight-night-page-vs-ruziboev-sep-05-2026/,2026-08-31
Морган Шарьер,Фелипе Лима,2.77,1.50,FightBot,https://fightbot.app/fights/morgan-charriere-vs-felipe-lima-8926,2026-08-31
Дэн Хукер,Саладин Парнасс,4.00,1.25,MMA Junkie,https://mmajunkie.usatoday.com/story/sports/ufc/2026/08/21/ufc-paris-dan-hooker-vs-salahdine-parnasse-betting-odds-mma-gambling/91401196007/,2026-08-31
'''
ds_df = pd.read_csv(StringIO(csv_like), sep=',')
ds_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Майкл Пэйдж,Нурсултон Рузибоев,1.64,2.44,Robinhood,https://robinhood.com/us/en/prediction-markets...,2026-08-31
1,Морган Шарьер,Фелипе Лима,2.77,1.50,FightBot,https://fightbot.app/fights/morgan-charriere-v...,2026-08-31
2,Дэн Хукер,Саладин Парнасс,4.00,1.25,MMA Junkie,https://mmajunkie.usatoday.com/story/sports/uf...,2026-08-31

## [алиса](https://alice.yandex.ru/)

In [91]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Дэн Хукер,Саладин Парнасс,4.70,1.20,betcity.ru,https://m.betcity.ru/ru/line/ufc/935727/23896962,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.85,1.95,draftkings.com,https://www.sportsbook.draftkings.com,2026-08-31
Фарес Зиам,Аксель Сола,2.10,1.80,bet365.com,https://www.bet365.com,2026-08-31
Лосене Кейта,Мухаммад Наимов,1.75,2.05,fon.bet,https://fon.bet/sports/mix-fights/category/ufc,2026-08-31
Морган Шарьер,Фелипе Лима,2.00,1.85,pari.ru,https://pari.ru,2026-08-31

'''
alice_df = pd.read_csv(StringIO(csv_like), sep=',')
alice_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Дэн Хукер,Саладин Парнасс,4.70,1.20,betcity.ru,https://m.betcity.ru/ru/line/ufc/935727/23896962,2026-08-31
1,Майкл Пэйдж,Нурсултон Рузибоев,1.85,1.95,draftkings.com,https://www.sportsbook.draftkings.com,2026-08-31
2,Фарес Зиам,Аксель Сола,2.10,1.80,bet365.com,https://www.bet365.com,2026-08-31
3,Лосене Кейта,Мухаммад Наимов,1.75,2.05,fon.bet,https://fon.bet/sports/mix-fights/category/ufc,2026-08-31
4,Морган Шарьер,Фелипе Лима,2.00,1.85,pari.ru,https://pari.ru,2026-08-31

## [ernie](https://chat.baidu.com/search/10481782372203716429?enter_type=sidebar_dialog)
[ernie alter](https://huggingface.co/spaces/baidu/ernie_x1_turbo_demo)
будто приводит от балды

In [92]:
csv_like='''

fighter1,fighter2,coef1,coef2,source,link,load_date


'''

ernie_df = pd.read_csv(StringIO(csv_like), sep=',')
ernie_df

Empty DataFrame
Columns: [fighter1, fighter2, coef1, coef2, source, link, load_date]
Index: []

## [giga](https://giga.chat/gigachat/)

мало, но тщательнее

- [пример старого прогноза](https://ironwin.ru/bukmekery/bukmeker-rasskazal-kak-razdelilis-stavki-na-boy-lopes-volkanovski-50-za-diego/)

In [93]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Дэн Хукер,Саладин Парнасс,3.3,1.28,Legalbet,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Умар Нурмагомедов,Сонг Ядонг,1.15,6.2,Sport-Express,https://www.sport-express.ru/martial/mma/ufc/news/umar-nurmagomedov-song-yadong-29-avgusta-2026-prognoz-koefficient-i-stavka-na-boy-ufc-kto-pobedit-2450638/,2026-08-31
'''
giga_df = pd.read_csv(StringIO(csv_like), sep=',')
giga_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Дэн Хукер,Саладин Парнасс,3.30,1.28,Legalbet,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
1,Умар Нурмагомедов,Сонг Ядонг,1.15,6.20,Sport-Express,https://www.sport-express.ru/martial/mma/ufc/n...,2026-08-31

## [perplexity](https://www.perplexity.ai/search)

In [94]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Майкл Альжаруж,Фабия Синтес,-230,+192,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Дельфин Бенуайш,София Монтенегро,+120,-140,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Матье Лето Дюкло,Диас Л Ф,+219,-265,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Нора Корноль,Сигула Клаудия,-180,+157,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Омар Си,Модестас Букаускас,-235,+195,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Кертис Кэмпбелл,Тревор Пик,-450,+350,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Мариу Пинту,Райан Спэнн,-325,+263,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Лосене Кейта,Мухаммад Наимов,-400,+316,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Морган Шарьер,Фелипе Лима,+109,-129,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Даниил Донченко,Пунахили Сориано,-300,+245,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,-165,+145,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Фарес Зиам,Аксель Сола,-175,+153,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Дэн Хукер,Саладин Парнасс,+275,-357,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Майкл Альжаруж,Фабия Синтес,-149,+123,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Дельфин Бенуайш,София Монтенегро,-155,+128,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Матье Лето Дюкло,Диас Л Ф,-112,-108,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Нора Корноль,Сигула Клаудия,-132,+109,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Омар Си,Модестас Букаускас,-191,+158,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Кертис Кэмпбелл,Тревор Пик,-323,+279,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Мариу Пинту,Райан Спэнн,-277,+228,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Лосене Кейта,Мухаммад Наимов,-341,+279,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Морган Шарьер,Фелипе Лима,-183,+158,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Даниил Донченко,Пунахили Сориано,-219,+189,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,-168,+140,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Фарес Зиам,Аксель Сола,-155,+128,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
Дэн Хукер,Саладин Парнасс,+397,-459,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31

'''
perp_df = pd.read_csv(StringIO(csv_like), sep=',')
perp_df
# perp_df = perp_df.drop_duplicates(subset=['link', 'fighter1'])

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Майкл Альжаруж,Фабия Синтес,-230,192,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
1,Дельфин Бенуайш,София Монтенегро,120,-140,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
2,Матье Лето Дюкло,Диас Л Ф,219,-265,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
3,Нора Корноль,Сигула Клаудия,-180,157,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
4,Омар Си,Модестас Букаускас,-235,195,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
5,Кертис Кэмпбелл,Тревор Пик,-450,350,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
6,Мариу Пинту,Райан Спэнн,-325,263,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
7,Лосене Кейта,Мухаммад Наимов,-400,316,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
8,Морган Шарьер,Фелипе Лима,109,-129,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
9,Даниил Донченко,Пунахили Сориано,-300,245,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
10,Майкл Пэйдж,Нурсултон Рузибоев,-165,145,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
11,Фарес Зиам,Аксель Сола,-175,153,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
12,Дэн Хукер,Саладин Парнасс,275,-357,MMA Odds Breaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
13,Майкл Альжаруж,Фабия Синтес,-149,123,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
14,Дельфин Бенуайш,София Монтенегро,-155,128,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
15,Матье Лето Дюкло,Диас Л Ф,-112,-108,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
16,Нора Корноль,Сигула Клаудия,-132,109,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
17,Омар Си,Модестас Букаускас,-191,158,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
18,Кертис Кэмпбелл,Тревор Пик,-323,279,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
19,Мариу Пинту,Райан Спэнн,-277,228,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
20,Лосене Кейта,Мухаммад Наимов,-341,279,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
21,Морган Шарьер,Фелипе Лима,-183,158,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
22,Даниил Донченко,Пунахили Сориано,-219,189,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
23,Майкл Пэйдж,Нурсултон Рузибоев,-168,140,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
24,Фарес Зиам,Аксель Сола,-155,128,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31
25,Дэн Хукер,Саладин Парнасс,397,-459,Best Fight Odds (FanDuel),https://www.bestfightodds.com/,2026-08-31

## [qwen](https://chat.qwen.ai/)

In [95]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Майкл Альжаруж,Фабия Синтес,1.61,2.22,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324853122660-aljarouj-michael-sintes-fabia,2026-08-31
Дельфин Бенуайш,София Монтенегро,1.64,2.17,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324853053554-benouaich-delphine-montenegro-sofia,2026-08-31
Матье Лето Дюкло,Диас Л Ф,1.95,1.79,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324852868576-duclos-matthieu-letho-dias-luis-felipe,2026-08-31
Нора Корноль,"Сигула, Клаудия",1.73,2.04,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324853122660-nora-cornolle-klaudia-sygula,2026-08-31
Омар Си,Модестас Букаускас,1.50,2.49,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324852975455-sy-oumar-bukauskas-modestas,2026-08-31
Кертис Кэмпбелл,Тревор Пик,1.28,3.50,Leon,https://leon.ru/bets/mma/1970324836974960-ufc,2026-08-31
Мариу Пинту,Райан Спэнн,1.38,3.15,Pari,https://pari.ru/sports/mix-fights/category/ufc/145585/67628592,2026-08-31
Лосене Кейта,Мухаммад Наимов,1.33,3.15,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324852975469-keita-losene-naimov-muhammadjon,2026-08-31
Морган Шарьер,Фелипе Лима,2.65,1.45,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-hooker-vs-parnasse/1970324852868577-charriere-morgan-lima-felipe,2026-08-31
Даниил Донченко,Пунахили Сориано,1.38,3.15,Fonbet,https://fon.bet/sports/mix-fights/category/ufc/145585/67627424,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.47,2.55,Leon,https://leon.ru/bets/mma/1970324836974960-ufc,2026-08-31
Фарес Зиам,Аксель Сола,1.65,2.30,Pari,https://pari.ru/sports/mix-fights/category/ufc,2026-08-31
Дэн Хукер,Саладин Парнасс,4.40,1.19,Leon,https://leon.ru/bets/mma/1970324836974960-ufc,2026-08-31

'''
qwen_df = pd.read_csv(StringIO(csv_like), sep=',')
qwen_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Майкл Альжаруж,Фабия Синтес,1.61,2.22,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
1,Дельфин Бенуайш,София Монтенегро,1.64,2.17,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
2,Матье Лето Дюкло,Диас Л Ф,1.95,1.79,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
3,Нора Корноль,"Сигула, Клаудия",1.73,2.04,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
4,Омар Си,Модестас Букаускас,1.50,2.49,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
5,Кертис Кэмпбелл,Тревор Пик,1.28,3.50,Leon,https://leon.ru/bets/mma/1970324836974960-ufc,2026-08-31
6,Мариу Пинту,Райан Спэнн,1.38,3.15,Pari,https://pari.ru/sports/mix-fights/category/ufc...,2026-08-31
7,Лосене Кейта,Мухаммад Наимов,1.33,3.15,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
8,Морган Шарьер,Фелипе Лима,2.65,1.45,Leon,https://leon.ru/bets/mma/ufc/ufc-fight-night-h...,2026-08-31
9,Даниил Донченко,Пунахили Сориано,1.38,3.15,Fonbet,https://fon.bet/sports/mix-fights/category/ufc...,2026-08-31
10,Майкл Пэйдж,Нурсултон Рузибоев,1.47,2.55,Leon,https://leon.ru/bets/mma/1970324836974960-ufc,2026-08-31
11,Фарес Зиам,Аксель Сола,1.65,2.30,Pari,https://pari.ru/sports/mix-fights/category/ufc,2026-08-31
12,Дэн Хукер,Саладин Парнасс,4.40,1.19,Leon,https://leon.ru/bets/mma/1970324836974960-ufc,2026-08-31

## [MiMo](https://huggingface.co/chat/conversation/6a69d974823ecd27b35ce1b2)

In [96]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
'''
mimo_df = pd.read_csv(StringIO(csv_like), sep=',')
mimo_df

Empty DataFrame
Columns: [fighter1, fighter2, coef1, coef2, source, link, load_date]
Index: []

## [llama](https://llama.online/chat)
[hf chat](https://huggingface.co/chat/conversation/6988186425454ac74973d837)
есть только общие ссылки

выведи 5 с корректным форматированием csv чтобы строки были разделены

In [97]:
csv_like = '''
"fighter1","fighter2","coef1","coef2","source","link","load_date"

'''
llama_df = pd.read_csv(StringIO(csv_like), sep=',')
llama_df

Empty DataFrame
Columns: [fighter1, fighter2, coef1, coef2, source, link, load_date]
Index: []

## [mistral](https://chat.mistral.ai/chat)

конкретные и верные почти все

In [98]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Дэн Хукер,Саладин Парнасс,4.00,1.25,MMA Junkie (BetWay),https://mmajunkie.usatoday.com/story/sports/ufc/2026/08/21/ufc-paris-dan-hooker-vs-salahdine-parnasse-betting-odds-mma-gambling/91401196007/,2026-08-31
Дэн Хукер,Саладин Парнасс,3.92,1.23,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
Дэн Хукер,Саладин Парнасс,4.57,1.20,BetUS,https://www.betus.com.pa/sportsbook/ufc/,2026-08-31
Дэн Хукер,Саладин Парнасс,3.75,1.28,Legalbet,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Фарес Зиам,Аксель Сола,1.43,2.22,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.96,1.45,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
Морган Шарьер,Фелипе Лима,2.13,1.12,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
Лосене Кейта,Мухаммад Наимов,1.33,1.28,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
Мариу Пинту,Райан Спэнн,1.06,2.63,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
Матье Лето Дюкло,Луис Фелипе Диас,1.95,1.95,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31
Дельфин Бенуайш,София Монтенегро,1.57,2.50,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31
Нора Корноль,Клаудия Сигула,1.75,2.10,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31
Майкл Альжаруж,Фабия Синтес,1.65,2.30,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31

'''
mist_df = pd.read_csv(StringIO(csv_like), sep=',')
mist_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Дэн Хукер,Саладин Парнасс,4.00,1.25,MMA Junkie (BetWay),https://mmajunkie.usatoday.com/story/sports/uf...,2026-08-31
1,Дэн Хукер,Саладин Парнасс,3.92,1.23,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
2,Дэн Хукер,Саладин Парнасс,4.57,1.20,BetUS,https://www.betus.com.pa/sportsbook/ufc/,2026-08-31
3,Дэн Хукер,Саладин Парнасс,3.75,1.28,Legalbet,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
4,Фарес Зиам,Аксель Сола,1.43,2.22,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
5,Майкл Пэйдж,Нурсултон Рузибоев,1.96,1.45,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
6,Морган Шарьер,Фелипе Лима,2.13,1.12,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
7,Лосене Кейта,Мухаммад Наимов,1.33,1.28,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
8,Мариу Пинту,Райан Спэнн,1.06,2.63,UFCalendar,https://www.ufcalendar.com/odds,2026-08-31
9,Матье Лето Дюкло,Луис Фелипе Диас,1.95,1.95,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31
10,Дельфин Бенуайш,София Монтенегро,1.57,2.50,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31
11,Нора Корноль,Клаудия Сигула,1.75,2.10,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31
12,Майкл Альжаруж,Фабия Синтес,1.65,2.30,OddsDigger,https://oddsdigger.com/ufc-mma,2026-08-31

## [google ИИ]

In [99]:


csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Дэн Хукер,Саладин Парнасс,4.33,1.22,BetWay,https://sports.yahoo.com/articles/ufc-fight-night-287-dan-175030528.html,2026-08-31
Дэн Хукер,Саладин Парнасс,3.35,1.21,Tapology,https://www.tapology.com/fightcenter/events/144513-ufc-fight-night,2026-08-31
Дэн Хукер,Саладин Парнасс,4.15,1.22,1xBet,https://www.oddssafari.com/matches/mma/ufc/hooker-d.-vs-parnasse-s./2297649,2026-08-31
Майкл Альжаруж,Фабия Синтес,1.65,2.27,Betano,https://www.betano.co/en/match-odds/michael-aljarouj-fabia-sintes/91462378/,2026-08-31
Майкл Альжаруж,Фабия Синтес,1.73,2.10,PaddyPower,https://www.paddypower.com/mixed-martial-arts/ufc-matches/michael-aljarouj-v-fabia-sintes-35981970,2026-08-31
Фарес Зиам,Аксель Сола,1.70,2.18,Betano,https://www.betano.co/en/match-odds/fares-ziam-axel-sola/91334573/,2026-08-31
Фарес Зиам,Аксель Сола,1.73,2.10,PaddyPower,https://www.paddypower.com/mixed-martial-arts/ufc-matches/fares-ziam-v-axel-sola-35981948,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.57,2.38,PaddyPower,https://www.paddypower.com/mixed-martial-arts/ufc-matches/michael-page-v-nursulton-ruziboev-35981947,2026-08-31
Даниил Донченко,Пунахили Сориано,1.50,2.63,PaddyPower,https://www.paddypower.com/mixed-martial-arts/ufc-matches/daniil-donchenko-v-punahele-soriano-35981949,2026-08-31
Даниил Донченко,Пунахили Сориано,1.45,2.75,BetWay,https://www.bestfightodds.com/,2026-08-31



'''
google_df = pd.read_csv(StringIO(csv_like), sep=',')
google_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Дэн Хукер,Саладин Парнасс,4.33,1.22,BetWay,https://sports.yahoo.com/articles/ufc-fight-ni...,2026-08-31
1,Дэн Хукер,Саладин Парнасс,3.35,1.21,Tapology,https://www.tapology.com/fightcenter/events/14...,2026-08-31
2,Дэн Хукер,Саладин Парнасс,4.15,1.22,1xBet,https://www.oddssafari.com/matches/mma/ufc/hoo...,2026-08-31
3,Майкл Альжаруж,Фабия Синтес,1.65,2.27,Betano,https://www.betano.co/en/match-odds/michael-al...,2026-08-31
4,Майкл Альжаруж,Фабия Синтес,1.73,2.10,PaddyPower,https://www.paddypower.com/mixed-martial-arts/...,2026-08-31
5,Фарес Зиам,Аксель Сола,1.70,2.18,Betano,https://www.betano.co/en/match-odds/fares-ziam...,2026-08-31
6,Фарес Зиам,Аксель Сола,1.73,2.10,PaddyPower,https://www.paddypower.com/mixed-martial-arts/...,2026-08-31
7,Майкл Пэйдж,Нурсултон Рузибоев,1.57,2.38,PaddyPower,https://www.paddypower.com/mixed-martial-arts/...,2026-08-31
8,Даниил Донченко,Пунахили Сориано,1.50,2.63,PaddyPower,https://www.paddypower.com/mixed-martial-arts/...,2026-08-31
9,Даниил Донченко,Пунахили Сориано,1.45,2.75,BetWay,https://www.bestfightodds.com/,2026-08-31

## [grok](https://huggingface.co/spaces/llamameta/Grok-4-heavy-free)
[родная сссылка, пока не доступна для РФ](https://x.ai/grok)

ссылки не проверяются, может из-за vpn

In [100]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Michael Aljarouj,Fabia Sintes,-150,+120,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Delphine Benouaich,Sofia Montenegro,-162,+130,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Matthieu Duclos,Luis Felipe Dias,-120,+105,bestfightodds,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Nora Cornolle,Klaudia Sygula,-125,+105,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Oumar Sy,Modestas Bukauskas,-186,+150,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Kurtis Campbell,Trevor Peek,-340,+270,bestfightodds/TheFightBrief,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Mario Pinto,Ryan Spann,-270,+220,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Losene Keita,Muhammad Naimov,-320,+235,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Morgan Charriere,Felipe Lima,+160,-200,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Daniil Donchenko,Punahele Soriano,-220,+180,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Michael Page,Nursulton Ruziboev,-180,+150,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Fares Ziam,Axel Sola,-160,+130,bestfightodds/CBS/UFC,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Dan Hooker,Salahdine Parnasse,+400,-600,bestfightodds/CBS/MMAJunkie/Unibet,https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
'''
grok_df = pd.read_csv(StringIO(csv_like), sep=',')
grok_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Michael Aljarouj,Fabia Sintes,-150,120,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
1,Delphine Benouaich,Sofia Montenegro,-162,130,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
2,Matthieu Duclos,Luis Felipe Dias,-120,105,bestfightodds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
3,Nora Cornolle,Klaudia Sygula,-125,105,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
4,Oumar Sy,Modestas Bukauskas,-186,150,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
5,Kurtis Campbell,Trevor Peek,-340,270,bestfightodds/TheFightBrief,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
6,Mario Pinto,Ryan Spann,-270,220,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
7,Losene Keita,Muhammad Naimov,-320,235,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
8,Morgan Charriere,Felipe Lima,160,-200,bestfightodds/Verdict,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
9,Daniil Donchenko,Punahele Soriano,-220,180,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
10,Michael Page,Nursulton Ruziboev,-180,150,bestfightodds/CBS,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
11,Fares Ziam,Axel Sola,-160,130,bestfightodds/CBS/UFC,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
12,Dan Hooker,Salahdine Parnasse,400,-600,bestfightodds/CBS/MMAJunkie/Unibet,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31

## chat gpt

In [101]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
"Майкл Альжаруж","Фабия Синтес",1.6667,2.35,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Дельфин Бенуайш","София Монтенегро",1.6452,2.45,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Матье Лето Дюкло","Диас Л Ф",1.8333,2.05,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Нора Корноль","Сигула, Клаудия",1.8,2.09,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Омар Си","Модестас Букаускас",1.5405,2.55,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Кертис Кэмпбелл","Тревор Пик",1.3003,3.70,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Мариу Пинту","Райан Спэнн",1.4,3.20,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Лосене Кейта","Мухаммад Наимов",1.3636,3.70,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Морган Шарьер","Фелипе Лима",2.70,1.50,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Даниил Донченко","Пунахили Сориано",1.4651,2.80,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Майкл Пэйдж","Нурсултон Рузибоев",1.5882,2.50,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Фарес Зиам","Аксель Сола",1.6667,2.35,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"
"Дэн Хукер","Саладин Парнасс",5.30,1.2222,"BestFightOdds","https://www.bestfightodds.com/events/ufc-fight-night-4326","2026-08-31"

'''
chat_df = pd.read_csv(StringIO(csv_like), sep=',')
chat_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Майкл Альжаруж,Фабия Синтес,1.6667,2.3500,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
1,Дельфин Бенуайш,София Монтенегро,1.6452,2.4500,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
2,Матье Лето Дюкло,Диас Л Ф,1.8333,2.0500,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
3,Нора Корноль,"Сигула, Клаудия",1.8000,2.0900,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
4,Омар Си,Модестас Букаускас,1.5405,2.5500,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
5,Кертис Кэмпбелл,Тревор Пик,1.3003,3.7000,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
6,Мариу Пинту,Райан Спэнн,1.4000,3.2000,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
7,Лосене Кейта,Мухаммад Наимов,1.3636,3.7000,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
8,Морган Шарьер,Фелипе Лима,2.7000,1.5000,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
9,Даниил Донченко,Пунахили Сориано,1.4651,2.8000,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
10,Майкл Пэйдж,Нурсултон Рузибоев,1.5882,2.5000,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
11,Фарес Зиам,Аксель Сола,1.6667,2.3500,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
12,Дэн Хукер,Саладин Парнасс,5.3000,1.2222,BestFightOdds,https://www.bestfightodds.com/events/ufc-fight...,2026-08-31

## [kimi](https://www.kimi.com/chat)

In [102]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Дэн Хукер,Саладин Парнасс,5.00,1.61,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Аксель Сола,Фарес Зиам,2.26,1.62,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.54,2.42,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Даниил Донченко,Пунахили Сориано,1.40,2.90,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Морган Шарьер,Фелипе Лима,2.62,1.48,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Лосене Кейта,Мухаммад Наимов,1.31,3.35,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Мариу Пинту,Райан Спэнн,1.36,3.10,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Кертис Кэмпбелл,Тревор Пик,1.27,3.65,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Майкл Альжаруж,Фабия Синтес,1.60,2.30,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Омар Си,Модестас Букаускас,1.49,2.58,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Нора Корноль,Сигула Клаудия,1.74,2.06,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Матье Лето Дюкло,Диас Л Ф,1.83,1.94,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
Дельфин Бенуайш,София Монтенегро,1.62,2.26,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight-night-4326,2026-08-31
'''
kimi_df = pd.read_csv(StringIO(csv_like), sep=',')
kimi_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Дэн Хукер,Саладин Парнасс,5.00,1.61,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
1,Аксель Сола,Фарес Зиам,2.26,1.62,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
2,Майкл Пэйдж,Нурсултон Рузибоев,1.54,2.42,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
3,Даниил Донченко,Пунахили Сориано,1.40,2.90,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
4,Морган Шарьер,Фелипе Лима,2.62,1.48,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
5,Лосене Кейта,Мухаммад Наимов,1.31,3.35,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
6,Мариу Пинту,Райан Спэнн,1.36,3.10,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
7,Кертис Кэмпбелл,Тревор Пик,1.27,3.65,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
8,Майкл Альжаруж,Фабия Синтес,1.60,2.30,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
9,Омар Си,Модестас Букаускас,1.49,2.58,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
10,Нора Корноль,Сигула Клаудия,1.74,2.06,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
11,Матье Лето Дюкло,Диас Л Ф,1.83,1.94,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31
12,Дельфин Бенуайш,София Монтенегро,1.62,2.26,FanDuel (via BestFightOdds),https://www.bestfightodds.com/events/ufc-fight...,2026-08-31

## minimax

In [103]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date


'''
minimax_df = pd.read_csv(StringIO(csv_like), sep=',')
minimax_df

Empty DataFrame
Columns: [fighter1, fighter2, coef1, coef2, source, link, load_date]
Index: []

## claude

In [104]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Майкл Альжаруж,Фабия Синтес,1.43,2.92,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Дельфин Бенуайш,София Монтенегро,2.20,1.71,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Матье Лето Дюкло,Диас Л Ф,3.19,1.38,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
"Нора Корноль","Сигула, Клаудия",1.56,2.57,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Омар Си,Модестас Букаускас,1.43,2.95,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Кертис Кэмпбелл,Тревор Пик,1.22,4.50,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Мариу Пинту,Райан Спэнн,1.31,3.63,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Лосене Кейта,Мухаммад Наимов,1.25,4.16,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Морган Шарьер,Фелипе Лима,2.09,1.78,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Даниил Донченко,Пунахили Сориано,1.33,3.45,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.61,2.45,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Фарес Зиам,Аксель Сола,1.57,2.53,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Дэн Хукер,Саладин Парнасс,3.75,1.28,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/opening-odds/161246-opening-betting-odds-for-ufc-paris-hooker-vs-parnasse/,2026-08-31
Майкл Альжаруж,Фабия Синтес,1.65,2.30,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Дельфин Бенуайш,София Монтенегро,1.63,2.35,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Матье Лето Дюкло,Диас Л Ф,2.00,1.83,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
"Нора Корноль","Сигула, Клаудия",1.77,2.10,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Омар Си,Модестас Букаускас,1.54,2.55,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Кертис Кэмпбелл,Тревор Пик,1.29,3.70,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Мариу Пинту,Райан Спэнн,1.38,3.10,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Лосене Кейта,Мухаммад Наимов,1.33,3.40,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Морган Шарьер,Фелипе Лима,2.70,1.49,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.50,2.65,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Фарес Зиам,Аксель Сола,1.67,2.25,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Дэн Хукер,Саладин Парнасс,4.75,1.20,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-september-05-2026,2026-08-31
Дэн Хукер,Саладин Парнасс,4.10,1.19,Winline,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Дэн Хукер,Саладин Парнасс,4.40,1.19,Leon,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Дэн Хукер,Саладин Парнасс,4.15,1.25,Fonbet,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Дэн Хукер,Саладин Парнасс,3.98,1.24,BetBoom,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Дэн Хукер,Саладин Парнасс,4.15,1.25,Bettery,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Дэн Хукер,Саладин Парнасс,4.10,1.24,БЕТСИТИ,https://legalbet.ru/best-posts/62028011-huker-parnass-stavki-i-koeffitcienti-na-boj/,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.54,2.26,Winline,https://legalbet.ru/best-posts/62028072-pejdzh-ruziboev-stavki-i-koeffitcienti-na-boj/,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.47,2.55,Leon,https://legalbet.ru/best-posts/62028072-pejdzh-ruziboev-stavki-i-koeffitcienti-na-boj/,2026-08-31
Майкл Пэйдж,Нурсултон Рузибоев,1.47,2.56,BetBoom,https://legalbet.ru/best-posts/62028072-pejdzh-ruziboev-stavki-i-koeffitcienti-na-boj/,2026-08-31

'''
claude_df = pd.read_csv(StringIO(csv_like), sep=',')
claude_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Майкл Альжаруж,Фабия Синтес,1.43,2.92,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
1,Дельфин Бенуайш,София Монтенегро,2.20,1.71,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
2,Матье Лето Дюкло,Диас Л Ф,3.19,1.38,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
3,Нора Корноль,"Сигула, Клаудия",1.56,2.57,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
4,Омар Си,Модестас Букаускас,1.43,2.95,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
5,Кертис Кэмпбелл,Тревор Пик,1.22,4.50,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
6,Мариу Пинту,Райан Спэнн,1.31,3.63,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
7,Лосене Кейта,Мухаммад Наимов,1.25,4.16,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
8,Морган Шарьер,Фелипе Лима,2.09,1.78,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
9,Даниил Донченко,Пунахили Сориано,1.33,3.45,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
10,Майкл Пэйдж,Нурсултон Рузибоев,1.61,2.45,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
11,Фарес Зиам,Аксель Сола,1.57,2.53,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
12,Дэн Хукер,Саладин Парнасс,3.75,1.28,MMAOddsBreaker,https://www.mmaoddsbreaker.com/fight-odds/open...,2026-08-31
13,Майкл Альжаруж,Фабия Синтес,1.65,2.30,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
14,Дельфин Бенуайш,София Монтенегро,1.63,2.35,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
15,Матье Лето Дюкло,Диас Л Ф,2.00,1.83,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
16,Нора Корноль,"Сигула, Клаудия",1.77,2.10,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
17,Омар Си,Модестас Букаускас,1.54,2.55,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
18,Кертис Кэмпбелл,Тревор Пик,1.29,3.70,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
19,Мариу Пинту,Райан Спэнн,1.38,3.10,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
20,Лосене Кейта,Мухаммад Наимов,1.33,3.40,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
21,Морган Шарьер,Фелипе Лима,2.70,1.49,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
22,Майкл Пэйдж,Нурсултон Рузибоев,1.50,2.65,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
23,Фарес Зиам,Аксель Сола,1.67,2.25,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
24,Дэн Хукер,Саладин Парнасс,4.75,1.20,bet365 (via UFC.com),https://www.ufc.com/event/ufc-fight-night-sept...,2026-08-31
25,Дэн Хукер,Саладин Парнасс,4.10,1.19,Winline,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
26,Дэн Хукер,Саладин Парнасс,4.40,1.19,Leon,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
27,Дэн Хукер,Саладин Парнасс,4.15,1.25,Fonbet,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
28,Дэн Хукер,Саладин Парнасс,3.98,1.24,BetBoom,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
29,Дэн Хукер,Саладин Парнасс,4.15,1.25,Bettery,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
30,Дэн Хукер,Саладин Парнасс,4.10,1.24,БЕТСИТИ,https://legalbet.ru/best-posts/62028011-huker-...,2026-08-31
31,Майкл Пэйдж,Нурсултон Рузибоев,1.54,2.26,Winline,https://legalbet.ru/best-posts/62028072-pejdzh...,2026-08-31
32,Майкл Пэйдж,Нурсултон Рузибоев,1.47,2.55,Leon,https://legalbet.ru/best-posts/62028072-pejdzh...,2026-08-31
33,Майкл Пэйдж,Нурсултон Рузибоев,1.47,2.56,BetBoom,https://legalbet.ru/best-posts/62028072-pejdzh...,2026-08-31

## tencent

In [105]:
csv_like = '''

fighter1,fighter2,coef1,coef2,source,link,load_date
Michael Aljaruj,Fabia Sintes,4.50,1.22,BestFightOdds,https://www.bestfightodds.com,2025-03-15
Dione Barbosa,Miranda Maverick,2.10,1.75,Pari.ru,https://pari.ru,2025-03-15
Matheus Nicolau,Asu Almabayev,1.61,2.30,Bet365,https://www.bet365.com,2025-03-15
Nora Cornolle,Jacqueline Cavalcanti,2.90,1.40,BetMGM,https://www.betmgm.com,2025-03-15
Oumar Sy,Rodolfo Bellato,1.45,2.75,DraftKings,https://sportsbook.draftkings.com,2025-03-15
Curtis Campbell,Trevor Peek,2.20,1.67,Fon.bet,https://fon.bet,2025-03-15
Mario Pinto,Ryan Spann,3.10,1.36,Winline,https://winline.ru,2025-03-15
Losene Keita,Muhammad Naimov,2.65,1.47,BestFightOdds,https://www.bestfightodds.com,2025-03-15
Morgan Charriere,Felipe Lima,1.83,1.95,Leon,https://leon.ru,2025-03-15
Daniel Santos,Javid Basharat,1.90,1.90,bet365,https://www.bet365.com,2025-03-15
Michael Page,Sharabutdin Magomedov,1.72,2.10,BestFightOdds,https://www.bestfightodds.com,2025-03-15
Fares Ziam,Kaan Ofli,1.30,3.50,Ligastavok,https://www.ligastavok.ru,2025-03-15
Dan Hooker,Mateusz Gamrot,2.40,1.57,Tapology,https://www.tapology.com,2025-03-15

'''
ten_df = pd.read_csv(StringIO(csv_like), sep=',')
ten_df

,fighter1,fighter2,coef1,coef2,source,link,load_date
0,Michael Aljaruj,Fabia Sintes,4.50,1.22,BestFightOdds,https://www.bestfightodds.com,2025-03-15
1,Dione Barbosa,Miranda Maverick,2.10,1.75,Pari.ru,https://pari.ru,2025-03-15
2,Matheus Nicolau,Asu Almabayev,1.61,2.30,Bet365,https://www.bet365.com,2025-03-15
3,Nora Cornolle,Jacqueline Cavalcanti,2.90,1.40,BetMGM,https://www.betmgm.com,2025-03-15
4,Oumar Sy,Rodolfo Bellato,1.45,2.75,DraftKings,https://sportsbook.draftkings.com,2025-03-15
5,Curtis Campbell,Trevor Peek,2.20,1.67,Fon.bet,https://fon.bet,2025-03-15
6,Mario Pinto,Ryan Spann,3.10,1.36,Winline,https://winline.ru,2025-03-15
7,Losene Keita,Muhammad Naimov,2.65,1.47,BestFightOdds,https://www.bestfightodds.com,2025-03-15
8,Morgan Charriere,Felipe Lima,1.83,1.95,Leon,https://leon.ru,2025-03-15
9,Daniel Santos,Javid Basharat,1.90,1.90,bet365,https://www.bet365.com,2025-03-15
10,Michael Page,Sharabutdin Magomedov,1.72,2.10,BestFightOdds,https://www.bestfightodds.com,2025-03-15
11,Fares Ziam,Kaan Ofli,1.30,3.50,Ligastavok,https://www.ligastavok.ru,2025-03-15
12,Dan Hooker,Mateusz Gamrot,2.40,1.57,Tapology,https://www.tapology.com,2025-03-15

## Сохранение

In [108]:
from datetime import datetime
slice_date = datetime.now().strftime('%Y-%m-%d')

In [109]:

# df = claude_df.assign(llm='claude').assign(manual_load = slice_date)

df = pd.concat([llama_df.assign(llm='llama'), google_df.assign(llm='google'), mist_df.assign(llm='mistral'),  grok_df.assign(llm='grok'),  mimo_df.assign(llm='mimo'),
                alice_df.assign(llm='alice'), kimi_df.assign(llm='kimi'), ernie_df.assign(llm='ernie'), giga_df.assign(llm='gigachat'), 
                ds_df.assign(llm='deepseek'), perp_df.assign(llm='perplexity'), qwen_df.assign(llm='qwen'), chat_df.assign(llm='chatgpt'),
               minimax_df.assign(llm='minimax'), claude_df.assign(llm='claude'), ten_df.assign(llm='tencent')], axis=0)\
        .assign(manual_load = slice_date)
df

C:\Users\admin\AppData\Local\Temp\ipykernel_19212\283164497.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([llama_df.assign(llm='llama'), google_df.assign(llm='google'), mist_df.assign(llm='mistral'),  grok_df.assign(llm='grok'),  mimo_df.assign(llm='mimo'),

,fighter1,fighter2,coef1,coef2,source,link,load_date,llm,manual_load
0,Дэн Хукер,Саладин Парнасс,4.33,1.22,BetWay,https://sports.yahoo.com/articles/ufc-fight-ni...,2026-08-31,google,2026-08-31
1,Дэн Хукер,Саладин Парнасс,3.35,1.21,Tapology,https://www.tapology.com/fightcenter/events/14...,2026-08-31,google,2026-08-31
2,Дэн Хукер,Саладин Парнасс,4.15,1.22,1xBet,https://www.oddssafari.com/matches/mma/ufc/hoo...,2026-08-31,google,2026-08-31
3,Майкл Альжаруж,Фабия Синтес,1.65,2.27,Betano,https://www.betano.co/en/match-odds/michael-al...,2026-08-31,google,2026-08-31
4,Майкл Альжаруж,Фабия Синтес,1.73,2.10,PaddyPower,https://www.paddypower.com/mixed-martial-arts/...,2026-08-31,google,2026-08-31
...,...,...,...,...,...,...,...,...,...
8,Morgan Charriere,Felipe Lima,1.83,1.95,Leon,https://leon.ru,2025-03-15,tencent,2026-08-31
9,Daniel Santos,Javid Basharat,1.90,1.90,bet365,https://www.bet365.com,2025-03-15,tencent,2026-08-31
10,Michael Page,Sharabutdin Magomedov,1.72,2.10,BestFightOdds,https://www.bestfightodds.com,2025-03-15,tencent,2026-08-31
11,Fares Ziam,Kaan Ofli,1.30,3.50,Ligastavok,https://www.ligastavok.ru,2025-03-15,tencent,2026-08-31
12,Dan Hooker,Mateusz Gamrot,2.40,1.57,Tapology,https://www.tapology.com,2025-03-15,tencent,2026-08-31

In [110]:
import shutil

old_df = pd.read_csv(conf['inference']['llm_coef_fn'])

shutil.move(conf['inference']['llm_coef_fn'], f'data/arch/llm_coefs_{slice_date}.csv')



df = pd.concat([old_df, df], ignore_index=True)

In [111]:
df.shape, old_df.shape

((6579, 11), (6421, 11))

In [112]:
df.to_csv(conf['inference']['llm_coef_fn'], index=False)

In [113]:
df[df['name_fighter1'].notna()]

,fighter1,fighter2,coef1,coef2,source,link,load_date,llm,manual_load,name_fighter1,name_fighter2
3363,NaN,NaN,1.45,2.7,forebet,https://www.forebet.com/ru/mma/predictions/202...,2026-04-22,gigachat,2026-04-23,Майра Буэно Сильва,Мишель Монтегю
3364,NaN,NaN,1.8,1.95,forebet,https://www.forebet.com/ru/mma/predictions/202...,2026-04-22,gigachat,2026-04-23,Дэйви Грант,Луна Мартинетти Хуан Адриан
3365,NaN,NaN,1.6,2.3,betting-1,https://betting-1.ru/boi-stavki-na-ufc-266-fig...,2026-04-22,gigachat,2026-04-23,Рафа Гарсия,Александр Эрнандес
3366,NaN,NaN,1.75,2.1,betting-1,https://betting-1.ru/boi-stavki-na-ufc-266-fig...,2026-04-22,gigachat,2026-04-23,Норма Дюмонт Виана,Жоселин Эдвардс

## популярные ссылки

In [90]:
import re
old_df = pd.read_csv(conf['inference']['llm_coef_fn'])
', '.join(old_df['link'].str.extract(fr'(http(?:s)?://[^/]*)/', expand=False).value_counts().head(20).index.tolist())

'https://www.forbes.com, https://mmajunkie.usatoday.com, https://pari.ru, https://www.mmaoddsbreaker.com, https://www.espn.com, https://fightodds.io, https://www.covers.com, https://sports.yahoo.com, https://www.bookmaker.eu, https://fon.bet, https://sportsbook.draftkings.com, https://www.bet365.com, https://www.oddsshark.com, https://www.tapology.com, https://verdictmma.com, https://winline.ru, https://www.betmgm.com, https://www.betonline.ag, https://www.bestfightodds.com, https://www.wagertalk.com'

## перевод форматов

In [84]:
df = pd.read_csv(conf['inference']['llm_coef_fn'], dtype='str')
df['coef1t'] = pd.to_numeric(df['coef1'], errors='coerce')
df['coef2t'] = pd.to_numeric(df['coef2'], errors='coerce')
df['not_num'] = df['coef1t'].isnull() | df['coef2t'].isnull()

In [ ]:
american_coef_sel = (df['coef1'].str.contains(r'\+|\-', regex=True, na=False)) | (df['coef2'].str.contains(r'\+|\-', regex=True, na=False))
# не типа not numeric и хотя бы один с нереалистичным остатком для американских коэффициентов
nreal_american_coef_sel = (df.apply(lambda x: float(x['coef1'])%1>0 or float(x['coef2'])%1>0 if not x['not_num'] else False, axis=1))
real_american_coef_sel = sel & (~nreal_american_coef_sel)&(~df['not_num']) 


df.loc[real_american_coef_sel, 'tr_coef1'] = df.loc[real_american_coef_sel, 'coef1'].astype(float).map(lambda x: x/100 + 1 if x>0 else 100/abs(x) + 1)
df.loc[real_american_coef_sel, 'tr_coef2'] = df.loc[real_american_coef_sel, 'coef2'].astype(float).map(lambda x: x/100 + 1 if x>0 else 100/abs(x) + 1)

df['coef1'] = df['coef1t'].mask(real_american_coef_sel, df['tr_coef1']).mask(sel & nreal_american_coef_sel, np.nan)
df['coef2'] = df['coef2t'].mask(real_american_coef_sel, df['tr_coef2']).mask(sel & nreal_american_coef_sel, np.nan)

# Словарь имен бойцов

In [13]:
import pandas as pd

from ruamel.yaml import YAML
import re
import numpy as np

conf = YAML().load(open('params.yaml'))

In [14]:
query_name = 'UFC Fight Night: Имавов – Борральо'

coef_df = pd.read_excel(conf['inference']['coef_fn'])
coef_df = coef_df.assign(event_day=lambda x:pd.to_datetime(x['date'], format='%d.%m.%Y'))
if not query_name:
    pred_df = coef_df[(coef_df['event_day']==coef_df['event_day'].max()) & (coef_df['load_date']==coef_df['load_date'].max())]
else:
    sel = (coef_df['name']==query_name)
    sel = sel & (coef_df.load_date == coef_df.loc[sel, 'load_date'].max())
    pred_df = coef_df.loc[sel]

## DeepSeek

In [35]:
fighters_l = pd.concat([pred_df[['fighter1']].rename(columns={'fighter1':'fighter'}), pred_df[['fighter2']].rename(columns={'fighter2':'fighter'})])\
    .drop_duplicates()['fighter'].tolist()
fighters_l

['Шона Бэннон',
 'Андреас Густафссон',
 'Роберт Брисжек',
 'Сэм Паттерсон',
 'Марцин Тубура',
 'Омар Си',
 'Уильям Гомис',
 'Гарри Хардвик',
 'Патрисиу Фрейри',
 'Рус Макки',
 'Боладжи Оки',
 'Модестас Букаускас',
 'Бенуа Сен-Дени',
 'Нассурдин Имавов',
 'Сэм Хьюз',
 'Ринат Фахретдинов',
 'Брэд Таварес',
 'Трей Уотерс',
 'Анте Делия',
 'Брендсон Рибейро',
 'Роберт Рухала',
 'Кауэ Фернандес',
 'Лосене Кейта',
 'Аксель Сола',
 'Мэйсон Джонс',
 'Пол Крэйг',
 'Маурисио Раффи',
 'Кайо Борральо']

Я тебе передам список имен бойцов ufc на русском языке, а ты верни мне для каждого бойца имена на английском, следи за сохранением порядка, в качестве разделителя используй "—",  не пытайся менять имена:

In [44]:
s = '''Шона Бэннон—Shauna Bannon
Андреас Густафссон—Andreas Gustafsson
Роберт Брисжек—Robert Bryczek
Сэм Паттерсон—Sam Patterson
Марцин Тубура—Marcin Tybura
Омар Си—Omar Sy
Уильям Гомис—William Gomis
Гарри Хардвик—Harry Hardwick
Патрисиу Фрейри—Patricio Freire
Рус Макки—Rhys McKee
Боладжи Оки—Bolaji Oki
Модестас Букаускас—Modestas Bukauskas
Бенуа Сен-Дени—Benoit Saint Denis
Нассурдин Имавов—Nassourdine Imavov
Сэм Хьюз—Sam Hughes
Ринат Фахретдинов—Rinat Fakhretdinov
Брэд Таварес—Brad Tavares
Трей Уотерс—Trey Waters
Анте Делия—Ante Delija
Брендсон Рибейро—Brendson Ribeiro
Роберт Рухала—Robert Ruchala
Кауэ Фернандес—Caio Fernandes
Лосене Кейта—Loseine Keita
Аксель Сола—Axel Sola
Мэйсон Джонс—Mason Jones
Пол Крэйг—Paul Craig
Маурисио Раффи—Mauricio Ruffy
Кайо Борральо—Caio Borralho'''

items = [it for it in s.split('\n') if len(it)>0]

In [45]:
import pandas as pd

vocab_df = pd.DataFrame([(it.split('—')[0].strip(), it.split('—')[1].strip()) for it in items], columns=['name_rus', 'name_en_ds'])
vocab_df.head(2)

             name_rus          name_en_ds
0         Шона Бэннон       Shauna Bannon
1  Андреас Густафссон  Andreas Gustafsson

In [46]:
from metaphone import doublemetaphone

vocab_df['code'] = vocab_df['name_en_ds'].map(lambda x: doublemetaphone(x)[0])

vocab_df['manual_verified']=False

In [47]:
vocab_old_df = pd.read_csv(conf['inference']['vocab_fn'])

In [48]:
# То, что есть в старом и прошло проверку по всем датасетам - удаляем
names_ser = vocab_old_df.loc[((vocab_old_df.name_rus.isin(vocab_df.name_rus) & (vocab_old_df[['fighters_name', 'fights_name', 'ranks_name']].isna().sum(axis=1)==0))), 'name_rus']
vocab_df = vocab_df[~vocab_df.name_rus.isin(names_ser)]

In [49]:
# Имеется в старом словаре, но полностью не заполнено
vocab_df[(vocab_df.name_rus.isin(vocab_old_df.name_rus)) & (~vocab_df.name_rus.isin(names_ser))]

Empty DataFrame
Columns: [name_rus, name_en_ds, code, manual_verified]
Index: []

## ufcs stats names

In [14]:
from selenium import webdriver
browser = webdriver.Firefox()

In [15]:
browser.get('http://www.ufcstats.com/event-details/6e380a4d73ab4f0e')
browser.implicitly_wait(2)
html = browser.page_source

In [16]:
bsObj = BeautifulSoup(html, 'lxml')

fighters = bsObj.findAll('p', {'class':'b-fight-details__table-text'})

f_names = [tag.get_text().strip() for tag in fighters]
f_names = [it for it in f_names if it!='' and not 'Matchup' in it and not 'weight' in it]

site_df = pd.DataFrame({'name_en':f_names}).assign(code=lambda x: x['name_en'].map(lambda y: doublemetaphone(y)[0]))

In [50]:
vocab_df = vocab_df.merge(site_df, how='outer', on='code')

- если в соединении нет записи в fights, то будет и рус и name_en (name_en_ds), и code (code1) , как, видимо, в конце удалим запись, так как вряд ли в fights найдем
- если не будет записи на русском, надо сверху добавить рус и англ название (например, через deep seek)

### no rus

In [51]:
vocab_df[vocab_df['name_rus'].isna()]

Empty DataFrame
Columns: [name_rus, name_en_ds, code, manual_verified, name_en]
Index: []

### no ufc

In [56]:
vocab_df[vocab_df['name_en'].isna()]

Empty DataFrame
Columns: [name_rus, name_en_ds, code, manual_verified, name_en]
Index: []

In [57]:
vocab_df['name_en'] = vocab_df['name_en'].mask(vocab_df['name_en'].isna(), vocab_df['name_en_ds'])

## проверка по датасету бойцов

In [58]:
fighters_df = pd.read_csv(conf['inference']['fighters_fn'])
fighters_df['full_name'] = fighters_df['First'].str.cat(fighters_df['Last'], sep=' ', na_rep='')

In [59]:
fighters_part_df = fighters_df[['full_name']].drop_duplicates()

vocab_df = vocab_df.merge(fighters_part_df, how='left', left_on='name_en', right_on='full_name')\
        .assign(check_fighters=lambda x:np.where(x['full_name'].notna(), True, False))\
        .rename(columns={'full_name':'fighters_name'})

In [60]:
fighters_part_df['code'] = fighters_part_df['full_name'].map(lambda x: doublemetaphone(x)[0])

vocab_df = vocab_df.merge(fighters_part_df.groupby('code', as_index=False)['full_name'].agg(list).rename(columns={'full_name':'fighters_alt'}), on='code', how='left')

## проверка по датасету боев

In [61]:
from src.prep_funcs import prep_strikes_fn

fights_df = pd.read_csv(conf['inference']['fights_fn'])

C:\Users\admin\AppData\Local\Temp\ipykernel_12572\1519535284.py:3: DtypeWarning: Columns (205,206,207,208) have mixed types. Specify dtype option on import or set low_memory=False.
  fights_df = pd.read_csv(conf['inference']['fights_fn'])

In [62]:
fighters_from_fights = pd.concat([fights_df[['Fighter_left']].rename(columns={'Fighter_left':'name'}), 
fights_df[['Fighter_right']].rename(columns={'Fighter_right':'name'})], axis=0).drop_duplicates()

In [63]:
vocab_df = vocab_df.merge(fighters_from_fights, how='left', left_on='name_en', right_on='name')\
        .assign(check_fights=lambda x:np.where(x['name'].notna(), True, False))\
        .rename(columns={'name':'fights_name'})

In [64]:
fighters_from_fights['code'] = fighters_from_fights['name'].map(lambda x: doublemetaphone(x)[0])

vocab_df = vocab_df.merge(fighters_from_fights.groupby('code', as_index=False)['name'].agg(list).rename(columns={'name':'fights_alt'}), on='code', how='left')

## проверка по датасету рангов

In [65]:
rank_big_df = pd.read_csv(conf['inference']['rankings_big_fn'])
rank_big_df.name = rank_big_df.name.str.replace(r'\s*".+"\s*', r' ', regex=True)
rank_big_df.name = rank_big_df.name.str.strip()

In [66]:
rank_part_df = rank_big_df[['name']].drop_duplicates()

vocab_df = vocab_df.merge(rank_part_df, how='left', left_on='name_en', right_on='name')\
        .assign(check_ranks=lambda x:np.where(x['name'].notna(), True, False))\
        .rename(columns={'name':'ranks_name'})

In [67]:
rank_part_df['code'] = rank_part_df['name'].map(lambda x: doublemetaphone(x)[0])

vocab_df = vocab_df.merge(rank_part_df.groupby('code', as_index=False)['name'].agg(list).rename(columns={'name':'ranks_alt'}), on='code', how='left')

In [68]:
vocab_df['names_dif_flag'] = (vocab_df['fighters_name']==vocab_df['fights_name'])&(vocab_df['fighters_name']==vocab_df['ranks_name'])

In [69]:
for col in ['ranks_alt', 'fights_alt', 'fighters_alt']:
    vocab_df[col] = vocab_df[col].apply(lambda x: x if isinstance(x, list) else [])

vocab_df['unique_alt_flag'] = vocab_df.apply(lambda x: len(set(x['fighters_alt'] + x['fights_alt'] + x['ranks_alt']))==1 and len(x['fighters_alt'])==1 and len(x['fights_alt'])==1 and len(x['ranks_alt'])==1, axis=1)

In [70]:
vocab_df = vocab_df.assign(auto_verified = (vocab_df.filter(regex='check').all(axis=1)) & (vocab_df['unique_alt_flag']) & (vocab_df['names_dif_flag']))
bad_sel = ~vocab_df['auto_verified']

## смотрим на хорошие

vocab_df[~bad_sel]

## смотрим на плохие

In [72]:
vocab_df[bad_sel]

,name_rus,name_en_ds,code,manual_verified,name_en,fighters_name,check_fighters,fighters_alt,fights_name,check_fights,fights_alt,ranks_name,check_ranks,ranks_alt,names_dif_flag,unique_alt_flag,auto_verified
7,Гарри Хардвик,Harry Hardwick,HRRTK,False,Harry Hardwick,NaN,False,[],NaN,False,[],NaN,False,[],False,False,False
8,Патрисиу Фрейри,Patricio Freire,PTRSFRR,False,Patricio Freire,Patricio Freire,True,[Patricio Freire],Patricio Freire,True,[Patricio Freire],NaN,False,[],False,False,False
12,Бенуа Сен-Дени,Benoit Saint Denis,PNTSNTTNS,False,Benoit Saint Denis,Benoit Saint Denis,True,[Benoit Saint Denis],Benoit Saint Denis,True,[Benoit Saint Denis],NaN,False,[],False,False,False
18,Анте Делия,Ante Delija,ANTTLJ,False,Ante Delija,Ante Delija,True,[Ante Delija],NaN,False,[],Ante Delija,True,[Ante Delija],False,False,False
20,Роберт Рухала,Robert Ruchala,RPRTRXL,False,Robert Ruchala,Robert Ruchala,True,[Robert Ruchala],NaN,False,[],NaN,False,[],False,False,False
21,Кауэ Фернандес,Caio Fernandes,KFRNNTS,False,Kaue Fernandes,Kaue Fernandes,True,[Kaue Fernandes],Kaue Fernandes,True,[Kaue Fernandes],NaN,False,[Kauê Fernandes],False,False,False
22,Лосене Кейта,Loseine Keita,LSNKT,False,Losene Keita,Losene Keita,True,[Losene Keita],NaN,False,[],NaN,False,[],False,False,False
23,Аксель Сола,Axel Sola,AKSLSL,False,Axel Sola,NaN,False,[],NaN,False,[],NaN,False,[],False,False,False

### альтернативные

In [73]:
sel = bad_sel & (vocab_df['unique_alt_flag'])

In [74]:
vocab_df[bad_sel & (vocab_df['unique_alt_flag'])]

Empty DataFrame
Columns: [name_rus, name_en_ds, code, manual_verified, name_en, fighters_name, check_fighters, fighters_alt, fights_name, check_fights, fights_alt, ranks_name, check_ranks, ranks_alt, names_dif_flag, unique_alt_flag, auto_verified]
Index: []

In [59]:
# можно брать из одного поля и первое, так как по unique_alt_flag только 1 значение везде
for col in ['fighters_name', 'fights_name', 'ranks_name']:
    vocab_df.loc[sel, col] = vocab_df.loc[sel, 'fights_alt'].map(lambda x: x[0])

In [75]:
vocab_df[bad_sel & (vocab_df['unique_alt_flag'])]

Empty DataFrame
Columns: [name_rus, name_en_ds, code, manual_verified, name_en, fighters_name, check_fighters, fighters_alt, fights_name, check_fights, fights_alt, ranks_name, check_ranks, ranks_alt, names_dif_flag, unique_alt_flag, auto_verified]
Index: []

- гуглим и выдает текущий турнир и прошлые бои, можно проверить

alt_name = 'Oumar Sy'
fights_df.loc[(fights_df['Fighter_left']==alt_name)| (fights_df['Fighter_right']==alt_name), 
['Date', 'Event', 'Fighter_left', 'Fighter_right', 'Win_lose_left']].sort_values(by='Date')

In [63]:
vocab_df.loc[bad_sel & (vocab_df['unique_alt_flag']), ['auto_verified', 'manual_verified']] = True

### нет альтернатив единых

1. Если знаем, что боец точно есть пытаемся найти его под другим именем
   ```
   fights_df[fights_df.Fighter_left.str.contains('Magomedov')]
   
   ```
   Если нашли, проще пойти в начало, заменить deep seek вариант и сюда спустится (так как вариант пройдет проверки и по другим датасетам проверки )
3. Если в датасете боев нет, то удаляем, так как для заданного момента времени бессмысленно таких искать. В будущем может появится потом, по наличию в датасете боев

In [76]:
vocab_df[bad_sel & (~vocab_df['unique_alt_flag'])]

,name_rus,name_en_ds,code,manual_verified,name_en,fighters_name,check_fighters,fighters_alt,fights_name,check_fights,fights_alt,ranks_name,check_ranks,ranks_alt,names_dif_flag,unique_alt_flag,auto_verified
7,Гарри Хардвик,Harry Hardwick,HRRTK,False,Harry Hardwick,NaN,False,[],NaN,False,[],NaN,False,[],False,False,False
8,Патрисиу Фрейри,Patricio Freire,PTRSFRR,False,Patricio Freire,Patricio Freire,True,[Patricio Freire],Patricio Freire,True,[Patricio Freire],NaN,False,[],False,False,False
12,Бенуа Сен-Дени,Benoit Saint Denis,PNTSNTTNS,False,Benoit Saint Denis,Benoit Saint Denis,True,[Benoit Saint Denis],Benoit Saint Denis,True,[Benoit Saint Denis],NaN,False,[],False,False,False
18,Анте Делия,Ante Delija,ANTTLJ,False,Ante Delija,Ante Delija,True,[Ante Delija],NaN,False,[],Ante Delija,True,[Ante Delija],False,False,False
20,Роберт Рухала,Robert Ruchala,RPRTRXL,False,Robert Ruchala,Robert Ruchala,True,[Robert Ruchala],NaN,False,[],NaN,False,[],False,False,False
21,Кауэ Фернандес,Caio Fernandes,KFRNNTS,False,Kaue Fernandes,Kaue Fernandes,True,[Kaue Fernandes],Kaue Fernandes,True,[Kaue Fernandes],NaN,False,[Kauê Fernandes],False,False,False
22,Лосене Кейта,Loseine Keita,LSNKT,False,Losene Keita,Losene Keita,True,[Losene Keita],NaN,False,[],NaN,False,[],False,False,False
23,Аксель Сола,Axel Sola,AKSLSL,False,Axel Sola,NaN,False,[],NaN,False,[],NaN,False,[],False,False,False

In [77]:
# убираем согласно фильтру сверху + условие на нулевые альтернативы по fights (по пункту 2) 
vocab_df = vocab_df[~(bad_sel & (~vocab_df['unique_alt_flag']) & (vocab_df['fights_alt'].str.len()==0))]

In [78]:
vocab_df[bad_sel & (~vocab_df['unique_alt_flag'])]

C:\Users\admin\AppData\Local\Temp\ipykernel_12572\851590646.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  vocab_df[bad_sel & (~vocab_df['unique_alt_flag'])]

,name_rus,name_en_ds,code,manual_verified,name_en,fighters_name,check_fighters,fighters_alt,fights_name,check_fights,fights_alt,ranks_name,check_ranks,ranks_alt,names_dif_flag,unique_alt_flag,auto_verified
8,Патрисиу Фрейри,Patricio Freire,PTRSFRR,False,Patricio Freire,Patricio Freire,True,[Patricio Freire],Patricio Freire,True,[Patricio Freire],NaN,False,[],False,False,False
12,Бенуа Сен-Дени,Benoit Saint Denis,PNTSNTTNS,False,Benoit Saint Denis,Benoit Saint Denis,True,[Benoit Saint Denis],Benoit Saint Denis,True,[Benoit Saint Denis],NaN,False,[],False,False,False
21,Кауэ Фернандес,Caio Fernandes,KFRNNTS,False,Kaue Fernandes,Kaue Fernandes,True,[Kaue Fernandes],Kaue Fernandes,True,[Kaue Fernandes],NaN,False,[Kauê Fernandes],False,False,False

#### проверка

In [102]:
alt_name = 'Morgan Charriere'
fights_df.loc[(fights_df['Fighter_left']==alt_name)| (fights_df['Fighter_right']==alt_name), 
['Date', 'Event', 'Fighter_left', 'Fighter_right', 'Win_lose_left']].sort_values(by='Date')

,Date,Event,Fighter_left,Fighter_right,Win_lose_left
7100,2023-09-02 00:00:00,UFC Fight Night: Gane vs. Spivac,Morgan Charriere,Manolo Zecchini,W
8658,2024-04-06 00:00:00,UFC Fight Night: Allen vs. Curtis 2,Morgan Charriere,Chepe Mariscal,L
8406,2024-09-28 00:00:00,UFC Fight Night: Moicano vs. Saint Denis,Morgan Charriere,Gabriel Miranda,W
8167,2025-03-22 00:00:00,UFC Fight Night: Edwards vs. Brady,Nathaniel Wood,Morgan Charriere,W
8692,2025-07-12 00:00:00,UFC Fight Night: Lewis vs. Teixeira,Nate Landwehr,Morgan Charriere,L

In [305]:
rank_big_df[rank_big_df['name'].str.contains('Grant')]

          division_name        date  rank                     name
166   light-heavyweight  2025-07-18    67               Grant Neal
410         lightweight  2025-07-18    11             Grant Dawson
628        bantamweight  2025-07-18    29  "Dangerous" Davey Grant
1471  light-heavyweight  2025-07-22    72               Grant Neal
1590       middleweight  2025-07-22    91             Dwight Grant
1709        lightweight  2025-07-22    10             Grant Dawson
1928       bantamweight  2025-07-22    29  "Dangerous" Davey Grant
2784  light-heavyweight  2025-07-27    84               Grant Neal
2893       middleweight  2025-07-27    94             Dwight Grant
3011        lightweight  2025-07-27    12             Grant Dawson
3225       bantamweight  2025-07-27    26  "Dangerous" Davey Grant
4064  light-heavyweight  2025-08-04    65               Grant Neal
4310        lightweight  2025-08-04    11             Grant Dawson
4519       bantamweight  2025-08-04    20  "Dangerous" Davey Grant

#### замены

In [83]:
vocab_df.loc[12, 'ranks_name'] = 'Benoit Saint Denis'

In [84]:
vocab_df[bad_sel & (~vocab_df['unique_alt_flag'])]

C:\Users\admin\AppData\Local\Temp\ipykernel_12572\851590646.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  vocab_df[bad_sel & (~vocab_df['unique_alt_flag'])]

,name_rus,name_en_ds,code,manual_verified,name_en,fighters_name,check_fighters,fighters_alt,fights_name,check_fights,fights_alt,ranks_name,check_ranks,ranks_alt,names_dif_flag,unique_alt_flag,auto_verified
8,Патрисиу Фрейри,Patricio Freire,PTRSFRR,True,Patricio Freire,Patricio Freire,True,[Patricio Freire],Patricio Freire,True,[Patricio Freire],Patricio Freire,False,[],False,False,False
12,Бенуа Сен-Дени,Benoit Saint Denis,PNTSNTTNS,True,Benoit Saint Denis,Benoit Saint Denis,True,[Benoit Saint Denis],Benoit Saint Denis,True,[Benoit Saint Denis],Benoit Saint Denis,False,[],False,False,False
21,Кауэ Фернандес,Caio Fernandes,KFRNNTS,True,Kaue Fernandes,Kaue Fernandes,True,[Kaue Fernandes],Kaue Fernandes,True,[Kaue Fernandes],Kauê Fernandes,False,[Kauê Fernandes],False,False,False

In [81]:
vocab_df.loc[[8, 12, 21], ['manual_verified']] = True

unpack_l = [12]
for ind in unpack_l:
    for col_pref in ['fights', 'fighters', 'ranks']:
        vocab_df.loc[ind, f'{col_pref}_name'] = vocab_df.loc[ind, f'{col_pref}_alt'][0]

Остальные не интересны, так как на них боев не будет и предсказаний не будет

## сохранение

In [85]:
primary_cols = ['name_rus', 'fighters_name', 'fights_name', 'ranks_name', 'manual_verified', 'auto_verified']

vocab_df = vocab_df.loc[(vocab_df.auto_verified==True) | (vocab_df.manual_verified==True), primary_cols]

In [87]:

vocab_df = pd.concat([vocab_df, vocab_old_df], ignore_index=True, axis=0)

In [88]:
vocab_df.to_csv(conf['inference']['vocab_fn'], index=False)

## manual changes

In [101]:
vocab_df = pd.read_csv(conf['inference']['vocab_fn'])

### add record

In [104]:
fights_df[fights_df.Fighter_left.str.contains('desa')]

,Event,Fighter_left,Fighter_right,Win_lose_left,Win_lose_right,Method:,Round:,Time:,Time format:,Referee:,...,Distance_l_5,Distance_r_5,Clinch_l_5,Clinch_r_5,Ground_l_5,Ground_r_5,judges,judge1,judge2,judge3
4591,UFC Fight Night: Poirier vs. Gaethje,Israel Adesanya,Marvin Vettori,W,L,Decision - Split,3,5:00,3 Rnd (5-5-5),Herb Dean,...,NaN,NaN,NaN,NaN,NaN,NaN,"[('Chris Hayes', '28', '29'), ('Chris Lee', '2...","('Chris Hayes', '28', '29')","('Chris Lee', '29', '28')","('Derek Cleary', '28', '29')"
4977,UFC 234: Adesanya vs. Silva,Israel Adesanya,Anderson Silva,W,L,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Herb Dean,...,NaN,NaN,NaN,NaN,NaN,NaN,"[('Garth Harriman', '28', '29'), ('Albert Shen...","('Garth Harriman', '28', '29')","('Albert Shen', '27', '30')","('Charlie Keech', '27', '30')"
5540,UFC 248: Adesanya vs. Romero,Israel Adesanya,Yoel Romero,W,L,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Dan Miragliotta,...,12 of 29,14 of 32,0 of 0,0 of 1,0 of 0,0 of 0,"[('Chris Lee', '46', '49'), (""Sal D'amato"", '4...","('Chris Lee', '46', '49')","(""Sal D'amato"", '47', '48')","('Ron McCarthy', '47', '48')"
5782,UFC 253: Adesanya vs. Costa,Israel Adesanya,Paulo Costa,W,L,KO/TKO,2,3:59,5 Rnd (5-5-5-5-5),Jason Herzog,...,NaN,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN
6151,UFC 263: Adesanya vs. Vettori 2,Israel Adesanya,Marvin Vettori,W,L,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Marc Goddard,...,11 of 26,9 of 23,0 of 1,0 of 0,0 of 0,0 of 0,"[('Derek Cleary', '45', '50'), (""Sal D'amato"",...","('Derek Cleary', '45', '50')","(""Sal D'amato"", '45', '50')","('Chris Flores', '45', '50')"
6470,UFC 271: Adesanya vs. Whittaker 2,Israel Adesanya,Robert Whittaker,W,L,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Herb Dean,...,12 of 21,8 of 17,1 of 1,2 of 2,0 of 0,0 of 0,NaN,NaN,NaN,NaN
6630,UFC 276: Adesanya vs. Cannonier,Israel Adesanya,Jared Cannonier,W,L,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Herb Dean,...,23 of 52,18 of 24,2 of 2,2 of 2,0 of 0,0 of 0,NaN,NaN,NaN,NaN
7088,UFC 293: Adesanya vs. Strickland,Israel Adesanya,Sean Strickland,L,W,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Marc Goddard,...,21 of 60,36 of 71,0 of 0,0 of 0,0 of 0,0 of 0,NaN,NaN,NaN,NaN
7539,UFC 281: Adesanya vs. Pereira,Israel Adesanya,Alex Pereira,L,W,KO/TKO,5,2:01,5 Rnd (5-5-5-5-5),Marc Goddard,...,7 of 13,25 of 34,2 of 2,3 of 3,0 of 0,0 of 0,NaN,NaN,NaN,NaN
7727,UFC 276: Adesanya vs. Cannonier,Israel Adesanya,Jared Cannonier,W,L,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Herb Dean,...,23 of 52,18 of 24,2 of 2,2 of 2,0 of 0,0 of 0,NaN,NaN,NaN,NaN
7952,UFC 271: Adesanya vs. Whittaker 2,Israel Adesanya,Robert Whittaker,W,L,Decision - Unanimous,5,5:00,5 Rnd (5-5-5-5-5),Herb Dean,...,12 of 21,8 of 17,1 of 1,2 of 2,0 of 0,0 of 0,NaN,NaN,NaN,NaN
8249,UFC Fight Night: Adesanya vs. Imavov,Israel Adesanya,Nassourdine Imavov,L,W,KO/TKO,2,0:30,5 Rnd (5-5-5-5-5),Marc Goddard,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
vocab_df = pd.concat([pd.DataFrame({'name_rus':'Исраэль Адесанья', 'fighters_name':'Israel Adesanya', 
              'fights_name':'Israel Adesanya', 'ranks_name':'Israel Adesanya', 'manual_verified':True, 'auto_verified':False}, index=[0]),
           vocab_df], ignore_index=True)

### правки

vocab_df.loc[vocab_df.name_rus=='Патрисиу Фрейри', 'ranks_name'] = None
vocab_df.loc[vocab_df.name_rus=='Бенуа Сен-Дени', 'ranks_name'] = None

### save

vocab_df.to_csv(conf['inference']['vocab_fn'], index=False)

# Ранги русские (ufc)
Не преобразовываем, если по ним подтягивается имя, то им доверяем, иначе большим рангам

In [72]:
# что делать с русскими рейтингами
rank_df = pd.read_csv('data/inference/rank_df.csv')

In [74]:
vocab_df

,name_rus,fighters_name,fights_name,ranks_name,manual_verified,auto_verified
0,Габриэлла Фернандес,Gabriella Fernandes,Gabriella Fernandes,Gabriella Fernandes,False,True
1,Жоселин Эдвардс,Joselyne Edwards,Joselyne Edwards,Joselyne Edwards,True,True
2,Элайджа Смит,Elijah Smith,Elijah Smith,Elijah Smith,False,True
3,Джулиус Уокер,Julius Walker,Julius Walker,Julius Walker,False,True
4,Эрик Андерс,Eryk Anders,Eryk Anders,Eryk Anders,True,True
5,Майлз Джонс,Miles Johns,Miles Johns,Miles Johns,False,True
6,Андре Фили,Andre Fili,Andre Fili,Andre Fili,True,False
7,Ясмин Лусиндо,Iasmin Lucindo,Iasmin Lucindo,Iasmin Lucindo,True,True
8,Роман Долидзе,Roman Dolidze,Roman Dolidze,Roman Dolidze,False,True
10,Присцилла Кашоэйра,Priscila Cachoeira,Priscila Cachoeira,Priscila Cachoeira,False,True
11,Тосиоми Казама,Toshiomi Kazama,Toshiomi Kazama,Toshiomi Kazama,False,True
12,Раффаэл Серкейра,Rafael Cerqueira,Rafael Cerqueira,Raffael Cerqueira,True,False
14,Жан Мацумото,Jean Matsumoto,Jean Matsumoto,Jean Matsumoto,False,True
15,Кристиан Родригес,Christian Rodriguez,Christian Rodriguez,Christian Rodriguez,False,True
16,Анджела Хилл,Angela Hill,Angela Hill,Angela Hill,False,True
17,Энтони Эрнандес,Anthony Hernandez,Anthony Hernandez,Anthony Hernandez,False,True

In [75]:
rank_df.merge(vocab_df, left_on='name', right_on='name_rus', how='inner')

,name,rank,direction,val,division_name,date,name_rus,fighters_name,fights_name,ranks_name,manual_verified,auto_verified
0,Роман Долидзе,8,NaN,NaN,Средний вес,2025-07-08,Роман Долидзе,Roman Dolidze,Roman Dolidze,Roman Dolidze,False,True
1,Роман Долидзе,8,NaN,NaN,Средний вес,2025-07-27,Роман Долидзе,Roman Dolidze,Roman Dolidze,Roman Dolidze,False,True
2,Роман Долидзе,9,decreased,1.0,Средний вес,2025-08-04,Роман Долидзе,Roman Dolidze,Roman Dolidze,Roman Dolidze,False,True
3,Ясмин Лусиндо,8,NaN,NaN,Женский минимальный вес,2025-07-08,Ясмин Лусиндо,Iasmin Lucindo,Iasmin Lucindo,Iasmin Lucindo,True,True
4,Ясмин Лусиндо,8,NaN,NaN,Женский минимальный вес,2025-07-27,Ясмин Лусиндо,Iasmin Lucindo,Iasmin Lucindo,Iasmin Lucindo,True,True
5,Ясмин Лусиндо,8,NaN,NaN,Женский минимальный вес,2025-08-04,Ясмин Лусиндо,Iasmin Lucindo,Iasmin Lucindo,Iasmin Lucindo,True,True
6,Анджела Хилл,12,NaN,NaN,Женский минимальный вес,2025-07-08,Анджела Хилл,Angela Hill,Angela Hill,Angela Hill,False,True
7,Анджела Хилл,12,NaN,NaN,Женский минимальный вес,2025-07-27,Анджела Хилл,Angela Hill,Angela Hill,Angela Hill,False,True
8,Анджела Хилл,12,NaN,NaN,Женский минимальный вес,2025-08-04,Анджела Хилл,Angela Hill,Angela Hill,Angela Hill,False,True